// Guia v2 (F1, 02-oct-2026): ruta vanilla, capitulos «Antes del primer jefe» y «Antes del modo
// difícil». Marcado: ver scratchpad F1-ESPEC-VANILLA.md ([[Nombre ingles exacto]] -> nombre
// oficial es-ES + sprite). Mecanicas verificadas en el decompilado de tModLoader 1.4.4.9:
//   - Ojo de Cthulhu natural: al anochecer, 1/3 si un jugador consumio >=5 Cristales de vida, tiene
//     defensa >10 y hay >=4 vecinos (Main.cs ~82964-82990).
//   - Invasiones: exigen un jugador con >=5 Cristales de vida (Main.StartInvasion ~82220). Invasion
//     duende natural: WorldGen.shadowOrbSmashed y 1/3 cada amanecer hasta vencerla (Main.cs ~83209).
//   - Tabernero: aparece cuando NPC.downedBoss2 (DD2Event.ReadyToFindBartender); nivel 2 con
//     modo dificil + cualquier mecanico; nivel 3 con modo dificil + Golem (DD2Event.cs ~98-120).
//   - Dios de las antorchas: >100 antorchas cerca, bajo la superficie, sin el favor ya en el
//     inventario (Player.cs ~16968-16980).
//   - Recetas y botin: tabla de referencias (extraer-obtencion.js sobre el codigo real).
'use strict';
const { B, P, PA, EQ, NPC, VIDA, CRISTALES, MANA, DEF, GANCHO, PUEBLO, MEJ, TODAS, ALGUNA, M, Z, PT, W } = require('./ayudas.js');

const CASCOS_METAL = ['Copper Helmet', 'Tin Helmet', 'Iron Helmet', 'Lead Helmet', 'Silver Helmet', 'Tungsten Helmet', 'Gold Helmet', 'Platinum Helmet'];
const PICOS_HIERRO_O_MEJOR = ['Iron Pickaxe', 'Lead Pickaxe', 'Silver Pickaxe', 'Tungsten Pickaxe', 'Gold Pickaxe', 'Platinum Pickaxe', 'Nightmare Pickaxe', 'Deathbringer Pickaxe', 'Molten Pickaxe'];

const paradas = [
  // =========================================================== Antes del primer jefe
  {
    id: 'inicio', capitulo: 'primeros-pasos', titulo: 'Tu primera base y tu primer equipo', tipo: 'preparacion',
    ubicaciones: [PT('spawn'), Z('superficie')],
    vida: { min: 100, max: 140, texto: '100–140' },
    donde: 'Cerca de tu punto de aparición, en la Superficie.',
    preparate: 'Las herramientas de cobre con las que empiezas, la madera que tales el primer día y antorchas. No hace falta nada más: esta parada es para montar la base antes de la primera noche.',
    porClase: {
      cuerpo_a_cuerpo: 'Una espada de madera o de metal te basta para la primera noche; el [[Wooden Boomerang]] de los cofres de superficie ayuda contra los ojos voladores.',
      distancia: 'Fabrica un [[Wooden Bow]] en la [[Work Bench]] y una pila de [[Wooden Arrow]]: dispara desde detrás de una puerta o de un muro de bloques.',
      magia: 'Busca un bastón de gema en cuanto encuentres amatistas o topacios: el [[Amethyst Staff]] se fabrica con barras de cobre en el yunque. Hasta entonces, defiéndete con la espada inicial.',
      invocacion: 'La primera arma de invocación llega pronto (látigos y bastones), pero la primera noche juegas con la espada inicial. Guarda las [[Gel]] que sueltan los slimes: hacen falta para antorchas y más adelante.',
    },
    tareas: [
      { condicion: M, texto: 'Tala árboles hasta tener al menos 100 de [[Wood]] y fabrica una [[Work Bench]], un [[Furnace]] y un yunque ([[Iron Anvil]] o [[Lead Anvil]]).' },
      { condicion: PUEBLO(2), texto: 'Construye un par de casas válidas (paredes de fondo, puerta, luz, mesa y silla). La guía lo da por hecho cuando tienes al menos dos vecinos en el pueblo además del [[Guide]].' },
      { condicion: EQ(...CASCOS_METAL), texto: 'Funde mineral y equípate la primera armadura de metal. La guía lo comprueba con el casco puesto.' },
      { condicion: PA(...PICOS_HIERRO_O_MEJOR), texto: 'Fabrica un pico de hierro o de plomo (o mejor): el de cobre no pica todos los minerales que vas a encontrar.' },
      { condicion: M, texto: 'Coloca cofres separados para materiales, equipo y pociones, y deja una cama cerca para fijar tu punto de aparición.' },
    ],
    combate: 'La primera noche aparecen zombis y ojos demoníacos. Quédate dentro de casa, con la puerta cerrada, y ataca desde dentro; si sales, no te alejes de la luz.',
    desbloquea: 'Con casas libres empiezan a llegar vecinos: el [[Merchant]] cuando llevas dinero encima y la [[Nurse]] cuando ya ha llegado el mercader y tienes más vida que al empezar. Consulta {a:vecinos}.',
    listoCuando: 'Tienes base con estaciones, una armadura de metal puesta y un pico de hierro o mejor.',
    completadaCuando: TODAS(EQ(...CASCOS_METAL), PA(...PICOS_HIERRO_O_MEJOR)),
    conserva: 'Las [[Gel]], la [[Wood]] y cualquier [[Fallen Star]] que recojas de noche.',
    avisos: [{ modos: ['viaje'], texto: 'En modo Viaje puedes duplicar objetos investigados: aun así, la ruta de esta guía sigue siendo válida como orden recomendado.' }],
    fuentes: [W('Guide:Walkthrough'), W('House'), W('Crafting stations')],
  },
  {
    id: 'subsuelo', capitulo: 'primeros-pasos', titulo: 'Bajo tierra: minería y cristales de vida', tipo: 'exploracion',
    ubicaciones: [Z('subsuelo'), Z('cavernas')],
    vida: { min: 140, max: 200, texto: '140–200' },
    donde: 'Subsuelo y Cavernas, empezando por debajo de tu base.',
    preparate: 'Armadura de metal, pico de hierro o mejor, muchas antorchas, cuerda o plataformas y unas cuantas [[Lesser Healing Potion]]. Lleva [[Bomb]] si las encuentras para abrir paso.',
    porClase: {
      cuerpo_a_cuerpo: 'Una espada ancha de metal o un yoyó de los cofres de las cavernas te dejan limpiar pasillos con seguridad.',
      distancia: 'Un arco de metal con flechas de madera; en cuanto puedas, compra munición mejor. Las [[Shuriken]] y los [[Throwing Knife]] también sirven en pasillos estrechos.',
      magia: 'El primer bastón de gema y algún [[Mana Crystal]]: se fabrican con 5 [[Fallen Star]], que caen del cielo de noche.',
      invocacion: 'Busca el [[Finch Staff]] en los árboles vivientes de la superficie o compra el [[Leather Whip]] a la [[n:Zoologist]] cuando el bestiario esté al 10 %.',
    },
    tareas: [
      { condicion: CRISTALES(5), texto: 'Rompe [[Life Crystal]] con el pico (corazones rojos incrustados en la roca) y úsalos. Con 5 llegas a 200 de vida.' },
      { condicion: PA('Magic Mirror', 'Ice Mirror'), texto: 'Encuentra un [[Magic Mirror]] (o su variante de hielo, el [[Ice Mirror]]) en los cofres del subsuelo: te devuelve a casa sin gastar nada.' },
      { condicion: PA('Gold Bar', 'Platinum Bar'), texto: 'Consigue mineral de oro o de platino y fúndelo: es la base de tu siguiente armadura y de la [[Gold Crown]] o [[Platinum Crown]].' },
      { condicion: MANA(60), clases: ['magia'], texto: 'Sube el maná a 60 con [[Mana Crystal]].' },
      { condicion: M, texto: 'Deja una línea de antorchas o un túnel recto desde tu base hasta las Cavernas para volver rápido.' },
    ],
    combate: 'En los túneles, los esqueletos y los murciélagos hacen más daño que los zombis. Coloca una plataforma sobre la que puedas esquivar y no bajes a ciegas a los huecos grandes: la caída hace daño.',
    desbloquea: 'Con 200 de vida y más de 10 de defensa el [[Eye of Cthulhu]] puede aparecer solo de noche si además tienes cuatro vecinos. Las invasiones (por ejemplo la Invasión duende) también exigen esos 200 de vida.',
    listoCuando: 'Tienes 200 de vida (5 cristales) y un espejo mágico o pociones para volver.',
    completadaCuando: CRISTALES(5),
    conserva: 'Las gemas (sobre todo [[Ruby]] y [[Diamond]]), los [[Life Crystal]] que no puedas usar todavía y las [[Fallen Star]].',
    avisos: [],
    fuentes: [W('Life Crystal'), W('Magic Mirror'), W('Underground'), W('Cavern')],
  },
  {
    id: 'pueblo', capitulo: 'primeros-pasos', titulo: 'Tus primeros vecinos', tipo: 'preparacion',
    ubicaciones: [PT('spawn'), Z('superficie')],
    vida: { min: 160, max: 200, texto: '160–200' },
    donde: 'Tu base, en la Superficie.',
    preparate: 'Material para tres o cuatro casas más y algo de dinero: el [[Merchant]] llega cuando tienes al menos 50 monedas de plata entre tus cosas.',
    porClase: {
      cuerpo_a_cuerpo: 'El [[Merchant]] vende el [[Shuriken]] y las primeras pociones; guarda dinero para el [[Arms Dealer]] solo si piensas combinar clases.',
      distancia: 'El [[Arms Dealer]] es tu vecino clave: llega cuando llevas un arma de fuego o munición y vende la [[Minishark]], el [[Flintlock Pistol]] y las [[Musket Ball]].',
      magia: 'El [[Merchant]] vende [[Lesser Mana Potion]]. Más adelante, el [[Wizard]] y la [[n:Dryad]] amplían tu equipo de magia.',
      invocacion: 'La [[n:Zoologist]] llega cuando tienes un 10 % del bestiario y vende el [[Leather Whip]] cuando el bestiario lo permite.',
    },
    tareas: [
      { condicion: NPC('Merchant'), texto: 'Recibe al [[Merchant]]: llévalo con 50 monedas de plata o más en el inventario y una casa libre.' },
      { condicion: NPC('Nurse'), texto: 'Recibe a la [[Nurse]], que te cura a cambio de dinero: llega cuando el mercader vive en el pueblo y tu vida supera la inicial.' },
      { condicion: ALGUNA(NPC('Arms Dealer'), NPC('Demolitionist')), texto: 'Consigue al [[Arms Dealer]] (lleva un arma de fuego o munición) o al [[Demolitionist]] (lleva un explosivo).' },
      { condicion: PUEBLO(4), texto: 'Llega a cuatro vecinos en el pueblo: es una de las condiciones para que el [[Eye of Cthulhu]] aparezca solo.' },
    ],
    combate: 'Los vecinos se defienden poco al principio. Construye las casas juntas y cierra la base con puertas para que los zombis no los acosen de noche.',
    desbloquea: 'Tienda del mercader (pociones, cuerda, [[Piggy Bank]]), cura de la enfermera y, con el traficante de armas, munición a la venta. La felicidad de cada vecino abarata sus precios y, con dos vecinos contentos, puede vender pilones: ver {a:vecinos}.',
    listoCuando: 'Tienes al menos cuatro vecinos, entre ellos el mercader y la enfermera.',
    completadaCuando: PUEBLO(4),
    conserva: 'Una [[Piggy Bank]] en casa: guarda en ella el dinero que no necesites llevar encima.',
    avisos: [],
    fuentes: [W('NPCs'), W('House'), W('Merchant'), W('Nurse')],
  },
  {
    id: 'movilidad', capitulo: 'primeros-pasos', titulo: 'Movilidad: gancho, botas y salto', tipo: 'preparacion',
    ubicaciones: [Z('cavernas'), Z('cielo')],
    vida: { min: 180, max: 220, texto: '180–220' },
    donde: 'Cavernas (cofres y enemigos), Nieve y, si las alcanzas, las islas del Cielo.',
    preparate: 'Tu armadura de metal y espacio en el inventario: aquí se trata de recorrer cofres, no de luchar.',
    porClase: {},
    tareas: [
      { condicion: GANCHO(), texto: 'Fabrica un [[Grappling Hook]] con 3 [[Chain]] y un [[Hook]] (lo sueltan los esqueletos de las cavernas) o cómpraselo después al [[Goblin Tinkerer]].' },
      { condicion: PA('Hermes Boots', 'Flurry Boots', 'Sailfish Boots', 'Spectre Boots'), texto: 'Consigue unas botas de velocidad: las [[Hermes Boots]], las [[Flurry Boots]] (cofres de hielo) o las [[Sailfish Boots]] (cajas de pesca).' },
      { condicion: PA('Cloud in a Bottle', 'Blizzard in a Bottle', 'Sandstorm in a Bottle', 'Tsunami in a Bottle', 'Fart in a Jar'), texto: 'Consigue un salto extra: [[Cloud in a Bottle]], [[Blizzard in a Bottle]], [[Sandstorm in a Bottle]] o [[Fart in a Jar]].' },
      { condicion: PA('Shiny Red Balloon', 'Lucky Horseshoe', 'Aglet', 'Anklet of the Wind'), opcional: true, texto: 'Opcional: un accesorio más de movimiento, como el [[Shiny Red Balloon]], la [[Lucky Horseshoe]] (sin daño por caída) o la [[Aglet]].' },
    ],
    combate: 'Con botas y salto doble ya no peleas en el sitio: corre en línea recta y salta sobre los ataques. Es la base para todos los jefes de esta guía.',
    desbloquea: 'Con el [[Goblin Tinkerer]] (tras la Invasión duende) podrás combinar estos accesorios en uno solo en el [[Tinkerer\'s Workshop]], y así liberar huecos.',
    listoCuando: 'Llevas gancho y unas botas de velocidad.',
    completadaCuando: TODAS(GANCHO(), PA('Hermes Boots', 'Flurry Boots', 'Sailfish Boots', 'Spectre Boots')),
    conserva: 'Las botas y las botellas de salto: se combinan después en las [[Spectre Boots]] y en accesorios de salto múltiple.',
    avisos: [],
    fuentes: [W('Grappling hooks'), W('Hermes Boots'), W('Cloud in a Bottle'), W('Accessories')],
  },
  {
    id: 'slime', capitulo: 'primeros-pasos', titulo: '[[King Slime]]', tipo: 'jefe', opcional: true, jefes: ['King Slime'],
    ubicaciones: [Z('superficie')],
    vida: { min: 200, max: 240, texto: '200–240' },
    donde: 'Superficie. Aparece solo en los bordes exteriores del mundo, al final de una Lluvia de slime o con su invocador.',
    invocacion: { objeto: 'Slime Crown', donde: 'En la Superficie, de día o de noche.', notas: 'Se fabrica en un altar demoníaco o carmesí con 20 [[Gel]] y una [[Gold Crown]] o [[Platinum Crown]].' },
    preparate: 'Armadura de oro, platino o equivalente, una plataforma ancha y un arma que ataque a distancia o con alcance.',
    porClase: {
      cuerpo_a_cuerpo: 'Una espada ancha de metal o un yoyó; el [[Enchanted Boomerang]] o el [[Wooden Boomerang]] ayudan cuando salta.',
      distancia: 'Arco de oro o de platino con [[Flaming Arrow]] o flechas de madera; dispara mientras te alejas.',
      magia: 'Bastón de gema (zafiro o superior) y pociones de maná.',
      invocacion: 'El [[Finch Staff]] o un látigo temprano; los esbirros se encargan de los slimes pequeños.',
    },
    tareas: [
      { condicion: ALGUNA(P('Slime Crown'), B('downedSlimeKing')), texto: 'Fabrica la [[Slime Crown]] o espera a que aparezca solo.' },
      { condicion: M, texto: 'Prepara una plataforma larga en el aire: así esquivas sus saltos por debajo.' },
      { condicion: B('downedSlimeKing'), texto: 'Derrótalo. En Experto o Maestro abre su bolsa del tesoro.' },
      { condicion: PA('Solidifier', 'Royal Gel'), texto: 'Guarda el [[Solidifier]] (y en Experto, el [[Royal Gel]], que hace que los slimes no te ataquen).' },
    ],
    combate: 'Salta, se teletransporta y suelta slimes pequeños. Mantente en movimiento horizontal y no te quedes bajo él cuando cae.',
    desbloquea: 'El [[Solidifier]] para fabricar objetos con gel. En Experto, el [[Royal Gel]].',
    listoCuando: 'Has derrotado al jefe o has decidido aplazarlo (es opcional).',
    completadaCuando: B('downedSlimeKing'),
    conserva: 'El [[Solidifier]] y el [[Royal Gel]].',
    avisos: [{ modos: ['clasico', 'viaje'], texto: 'En Clásico no hay bolsa del tesoro ni [[Royal Gel]]: el [[Solidifier]] cae directamente del jefe.' }],
    fuentes: [W('King Slime'), W('Slime Crown'), W('Slime Rain')],
  },
  {
    id: 'eye', capitulo: 'primeros-pasos', titulo: '[[Eye of Cthulhu]]', tipo: 'jefe', jefes: ['Eye of Cthulhu'],
    ubicaciones: [Z('superficie')],
    vida: { min: 200, max: 260, texto: '200–260' },
    donde: 'Superficie, de noche.',
    invocacion: { objeto: 'Suspicious Looking Eye', donde: 'De noche, en la Superficie.', notas: 'Se fabrica en un altar demoníaco o carmesí con 6 [[Lens]] (las sueltan los ojos demoníacos). Puede aparecer solo al anochecer (1 de cada 3 noches) si tienes 200 de vida, más de 10 de defensa y cuatro vecinos.' },
    preparate: 'Armadura de oro o platino, botas de velocidad, salto extra y una plataforma larga. Invoca al empezar la noche para tener tiempo.',
    porClase: {
      cuerpo_a_cuerpo: 'Una espada ancha de oro o platino, o el [[o:Enchanted Sword]] si lo encontraste; un yoyó como el [[Amazon]] o el [[Rally]] también rinde bien.',
      distancia: 'Arco de oro o de platino con [[Flaming Arrow]] o [[Jester\'s Arrow]]; o la [[Flintlock Pistol]] del traficante de armas.',
      magia: 'El [[Ruby Staff]] o el [[Diamond Staff]], o la [[Wand of Sparking]]; lleva pociones de maná.',
      invocacion: 'El [[Finch Staff]] o el [[Flinx Staff]], más un látigo para marcar al jefe.',
    },
    tareas: [
      { condicion: ALGUNA(P('Suspicious Looking Eye'), B('downedBoss1')), texto: 'Fabrica el [[Suspicious Looking Eye]] o cumple las condiciones para que aparezca solo.' },
      { condicion: M, texto: 'Construye una plataforma larga (unas 100 casillas) a cierta altura y, si quieres, unas hogueras para la regeneración.' },
      { condicion: B('downedBoss1'), texto: 'Derrótalo de noche.' },
      { condicion: PA('Demonite Ore', 'Crimtane Ore', 'Demonite Bar', 'Crimtane Bar'), texto: 'Recoge el [[Demonite Ore]] o el [[Crimtane Ore]] que suelta (depende de tu mundo).' },
      { condicion: EQ('Shield of Cthulhu'), texto: 'En Experto, equípate el [[Shield of Cthulhu]] de la bolsa: te da un embiste con doble pulsación lateral.' },
    ],
    combate: 'En la primera fase embiste y suelta siervos; en la segunda, sin pupila, embiste más rápido. Corre en horizontal y salta cuando venga hacia ti; ataca en las pausas entre embestidas.',
    desbloquea: 'El primer mineral del mal de tu mundo; con él y el de los propios biomas haces la [[Worm Food]] o la [[Bloody Spine]].',
    listoCuando: 'El jefe está vencido y tienes el mineral del mal (y el escudo en Experto).',
    completadaCuando: B('downedBoss1'),
    conserva: 'El [[Shield of Cthulhu]] y el mineral del mal.',
    avisos: [{ modos: ['clasico', 'viaje'], texto: 'En Clásico no hay bolsa del tesoro ni [[Shield of Cthulhu]]: marca esa tarea a mano y busca otro embiste más adelante (por ejemplo, el [[Tabi]] tras Plantera).' }],
    fuentes: [W('Eye of Cthulhu'), W('Suspicious Looking Eye')],
  },

  // =========================================================== Antes del modo dificil
  {
    id: 'lunasangre', capitulo: 'prehardmode', titulo: 'Luna de Sangre', tipo: 'evento', opcional: true,
    ubicaciones: [Z('superficie')],
    vida: { min: 200, max: 300, texto: '200–300' },
    donde: 'Superficie, cualquier noche (cuando el cielo y la luna se vuelven rojos).',
    invocacion: { objeto: 'Bloody Tear', donde: 'De noche.', notas: 'Opcional: la [[Bloody Tear]] la provoca a voluntad; sale de algunos enemigos de la propia Luna de Sangre.' },
    preparate: 'Casa cerrada con bloques en las puertas (los zombis abren puertas esta noche) y tu mejor arma.',
    porClase: {
      cuerpo_a_cuerpo: 'Espada ancha o yoyó: los zombis llegan en grupo.',
      distancia: 'Arma con munición perforante o de fuego desde un sitio alto.',
      magia: 'Un bastón que atraviese enemigos y pociones de maná de sobra.',
      invocacion: 'Los esbirros defienden bien la entrada. Si pescas esta noche puedes sacar el [[Vampire Frog Staff]].',
    },
    tareas: [
      { condicion: M, texto: 'Protege a tus vecinos: cierra las casas y no dejes huecos por donde entren los enemigos.' },
      { condicion: PA('Shark Tooth Necklace', 'Money Trough'), opcional: true, texto: 'Opcional: consigue el [[Shark Tooth Necklace]] o el [[Money Trough]], que sueltan los enemigos de esta noche (son raros).' },
      { condicion: P('Vampire Frog Staff'), clases: ['invocacion'], opcional: true, texto: 'Pesca durante la Luna de Sangre: los peces zombi pueden soltar el [[Vampire Frog Staff]].' },
    ],
    combate: 'Aparecen muchos más enemigos de lo normal. Lucha desde un punto elevado o una puerta y no te alejes de la luz.',
    desbloquea: 'Durante la Luna de Sangre la pesca da enemigos especiales y la [[Advanced Combat Techniques]] (ver {p:mejoras}).',
    listoCuando: 'Ha amanecido sin perder vecinos (o has aplazado este evento: es opcional).',
    completadaCuando: null,
    conserva: 'El [[Shark Tooth Necklace]] y la [[Bloody Tear]].',
    avisos: [],
    fuentes: [W('Blood Moon'), W('Bloody Tear')],
  },
  {
    id: 'evil', capitulo: 'prehardmode', titulo: '[[Eater of Worlds]] o [[Brain of Cthulhu]]', tipo: 'jefe', jefes: ['Eater of Worlds', 'Brain of Cthulhu'],
    ubicaciones: [Z('corrupcion', 'corrupcion'), Z('carmesi', 'carmesi')],
    vida: { min: 240, max: 300, texto: '240–300' },
    donde: 'La Corrupción o El Carmesí, según tu mundo, junto a los orbes sombríos o los corazones carmesíes del subsuelo.',
    invocacion: { objeto: null, donde: 'En el bioma del mal de tu mundo.', notas: 'Rompe tres orbes sombríos o corazones carmesíes con un martillo, o usa la [[Worm Food]] (Corrupción) o la [[Bloody Spine]] (Carmesí) dentro del bioma.' },
    preparate: 'Armadura de oro o platino (o meteorito), botas y salto. Contra el Devoramundos, un arma que atraviese o golpee en área; contra el Cerebro, una que apunte bien a un solo blanco.',
    porClase: {
      cuerpo_a_cuerpo: 'Una lanza o un yoyó atraviesa los segmentos del gusano; contra el Cerebro, cualquier espada ancha de metal sirve.',
      distancia: 'Flechas perforantes ([[Jester\'s Arrow]]) o la [[Minishark]] con mucha munición.',
      magia: 'El [[Vilethorn]] (Corrupción) o el [[Crimson Rod]] (Carmesí), y bastones de gema.',
      invocacion: 'Varios esbirros persiguen solos a los segmentos y a los siervos; el látigo marca al blanco.',
    },
    tareas: [
      { condicion: B('shadowOrbSmashed'), texto: 'Rompe tu primer orbe sombrío o corazón carmesí con un martillo: suelta un objeto y abre la puerta a la Invasión duende.' },
      { condicion: ALGUNA(P('Worm Food'), P('Bloody Spine'), B('downedBoss2')), texto: 'Fabrica la [[Worm Food]] o la [[Bloody Spine]] si prefieres invocar en lugar de romper el tercer orbe.' },
      { condicion: M, texto: 'Excava un túnel ancho y plano en el bioma (o una arena encima) para moverte sin chocar con bloques.' },
      { condicion: B('downedBoss2'), texto: 'Derrota al jefe del mal de tu mundo.' },
      { condicion: PA('Nightmare Pickaxe', 'Deathbringer Pickaxe'), texto: 'Fabrica la [[Nightmare Pickaxe]] o la [[Deathbringer Pickaxe]]: con ella podrás picar la [[Hellstone]] y el [[Meteorite]].' },
      { condicion: PA('Worm Scarf', 'Brain of Confusion'), texto: 'En Experto, guarda la [[Worm Scarf]] o el [[Brain of Confusion]] de la bolsa.' },
    ],
    combate: 'El Devoramundos se divide en gusanos más pequeños: concentra el daño y no te quedes encima del suelo que atraviesa. El Cerebro primero se esconde tras sus siervos y después embiste: cuando se vuelva visible, mantente lejos y apunta al cuerpo verdadero.',
    desbloquea: 'Escamas o muestras para la armadura de las sombras o la carmesí, el pico que pica la piedra infernal y el [[n:Tavernkeep]] (ver {p:dd2t1}).',
    listoCuando: 'El jefe del mal está vencido y tienes el pico de demonita o carmesí.',
    completadaCuando: B('downedBoss2'),
    conserva: 'Las [[Shadow Scale]] o [[Tissue Sample]] que te sobren, y el accesorio de Experto.',
    avisos: [{ modos: ['clasico', 'viaje'], texto: 'En Clásico no hay bolsa del tesoro: la [[Worm Scarf]] y el [[Brain of Confusion]] son de Experto. Marca esa tarea a mano.' }],
    fuentes: [W('Eater of Worlds'), W('Brain of Cthulhu'), W('Shadow Orb'), W('Crimson Heart')],
  },
  {
    id: 'meteorito', capitulo: 'prehardmode', titulo: 'El meteorito', tipo: 'exploracion', opcional: true,
    ubicaciones: [Z('meteorito'), Z('superficie')],
    vida: { min: 240, max: 300, texto: '240–300' },
    donde: 'Superficie. Al vencer por primera vez al jefe del mal de tu mundo cae un meteorito; después, 1 de cada 50 noches (y 1 de cada 2 veces que repites ese jefe).',
    preparate: 'La [[Nightmare Pickaxe]] o la [[Deathbringer Pickaxe]] (el [[Meteorite]] exige ese poder de pico) y algo de armadura: las cabezas de meteoro atacan mientras picas.',
    porClase: {
      cuerpo_a_cuerpo: 'El meteorito no da armas cuerpo a cuerpo destacadas: aprovecha para minar y seguir.',
      distancia: 'La [[Star Cannon]] (con la [[Minishark]] y [[Fallen Star]]) o la armadura de meteorito si usas armas de fuego.',
      magia: 'La [[Space Gun]] y la armadura de meteorito: juntas reducen mucho el coste de maná de la pistola.',
      invocacion: 'No hay piezas de invocación en el meteorito; sigue con la abeja reina.',
    },
    tareas: [
      { condicion: B('downedBoss2'), texto: 'Derrota al jefe del mal de tu mundo ({p:evil}): la primera vez cae un meteorito seguro.' },
      { condicion: M, texto: 'Localiza el cráter (el mensaje «Un meteorito ha aterrizado» avisa de la caída) y pica el [[Meteorite]].' },
      { condicion: PA('Meteor Helmet', 'Meteor Suit', 'Meteor Leggings'), clases: ['magia'], texto: 'Fabrica la armadura de meteorito: [[Meteor Helmet]], [[Meteor Suit]] y [[Meteor Leggings]].' },
      { condicion: PA('Space Gun', 'Star Cannon'), clases: ['magia', 'distancia'], texto: 'Fabrica la [[Space Gun]] (magia) o la [[Star Cannon]] (distancia).' },
    ],
    combate: 'Las [[n:Meteor Head]] vuelan atravesando bloques. Pica rápido y retírate a curarte si se juntan muchas.',
    desbloquea: 'Barras de meteorito para armadura y armas de magia y distancia.',
    listoCuando: 'Has fabricado lo que tu clase aprovecha del meteorito, o lo saltas (es opcional).',
    completadaCuando: PA('Meteor Helmet', 'Meteor Suit', 'Meteor Leggings', 'Space Gun', 'Star Cannon', 'Meteor Hamaxe'),
    conserva: 'Algo de [[Meteorite Bar]] para la [[Star Cannon]] si juegas a distancia.',
    avisos: [],
    fuentes: [W('Meteorite'), W('Meteor armor'), W('Space Gun')],
  },
  {
    id: 'goblins', capitulo: 'prehardmode', titulo: 'Invasión duende', tipo: 'evento', opcional: true,
    ubicaciones: [PT('spawn'), Z('superficie')],
    vida: { min: 240, max: 300, texto: '240–300' },
    donde: 'Llega a tu base desde uno de los lados del mundo.',
    invocacion: { objeto: 'Goblin Battle Standard', donde: 'En la Superficie.', notas: 'Aparece sola (1 de cada 3 amaneceres) tras romper un orbe sombrío o corazón carmesí, si tienes 200 de vida. El [[Goblin Battle Standard]] la provoca: se fabrica en el [[Loom]] con [[Tattered Cloth]] de los propios duendes.' },
    preparate: 'Tu mejor armadura previa al modo difícil, una pared o foso delante de las casas y un arma que golpee a varios enemigos.',
    porClase: {
      cuerpo_a_cuerpo: 'Armas de área o perforantes; la [[Blade of Grass]] o un yoyó son ideales.',
      distancia: 'Flechas perforantes o la [[Minishark]] desde un punto alto.',
      magia: 'Bastones que atraviesen; cuidado con los [[n:Goblin Sorcerer]], que se teletransportan.',
      invocacion: 'Los esbirros defienden las casas mientras tú te centras en los hechiceros.',
    },
    tareas: [
      { condicion: B('shadowOrbSmashed'), texto: 'Rompe un orbe sombrío o corazón carmesí: es la condición para que la invasión llegue sola.' },
      { condicion: CRISTALES(5), texto: 'Ten al menos 200 de vida (5 cristales): sin eso no empieza ninguna invasión.' },
      { condicion: B('downedGoblins'), texto: 'Derrota a la Invasión duende (la barra de progreso aparece arriba a la derecha).' },
      { condicion: NPC('Goblin Tinkerer'), texto: 'Busca al [[Bound Goblin]] en las Cavernas y libéralo: se convierte en el [[Goblin Tinkerer]].' },
      { condicion: P('Tinkerer\'s Workshop'), texto: 'Compra el [[Tinkerer\'s Workshop]] para combinar accesorios y usa su recombinación de modificadores para mejorar los tuyos.' },
    ],
    combate: 'Los duendes atraviesan puertas en grupo. Los [[n:Goblin Archer]] y los hechiceros son los peligrosos: elimínalos primero.',
    desbloquea: 'El [[Goblin Tinkerer]], el [[Tinkerer\'s Workshop]] y los accesorios combinados; los [[Rocket Boots]] a la venta.',
    listoCuando: 'Tienes el taller de chapuzas y combinas tus primeros accesorios.',
    completadaCuando: B('downedGoblins'),
    conserva: 'El [[Tattered Cloth]] (para volver a provocar la invasión) y los [[Spiky Ball]].',
    avisos: [],
    fuentes: [W('Goblin Army'), W('Goblin Tinkerer'), W('Tinkerer\'s Workshop')],
  },
  {
    id: 'dd2t1', capitulo: 'prehardmode', titulo: 'Ejército del Antiguo (nivel 1)', tipo: 'evento', opcional: true,
    ubicaciones: [PT('spawn'), Z('superficie')],
    vida: { min: 260, max: 320, texto: '260–320' },
    donde: 'Donde coloques el [[Eternia Crystal Stand]]: lo ideal es un terreno llano junto a tu base.',
    invocacion: { objeto: 'Eternia Crystal Stand', donde: 'Colócalo en un terreno con espacio a ambos lados.', notas: 'Pon un [[o:Eternia Crystal]] sobre el soporte y habla con el [[n:Tavernkeep]] para empezar. Los dos se compran al tabernero.' },
    preparate: 'Arma que golpee en área y los primeros centinelas del tabernero. Defiende el cristal: si lo destruyen, el evento falla.',
    porClase: {
      cuerpo_a_cuerpo: 'Una lanza o un yoyó y quedarte delante del cristal.',
      distancia: 'Dispara desde lo alto del soporte; los [[n:Etherian Goblin]] llegan por el suelo.',
      magia: 'Bastones de área y pociones de maná; los centinelas de fuego encajan bien.',
      invocacion: 'Los centinelas del tabernero son de invocación: coloca varios a ambos lados.',
    },
    tareas: [
      { condicion: NPC('Tavernkeep'), texto: 'Tras vencer al jefe del mal, busca al [[n:Tavernkeep]] dormido en la Superficie y despiértalo.' },
      { condicion: ALGUNA(P('Eternia Crystal Stand'), B('downedDD2InvasionT1')), texto: 'Compra el [[Eternia Crystal Stand]] y un [[o:Eternia Crystal]].' },
      { condicion: PA('Flameburst Rod', 'Ballista Rod', 'Explosive Trap Rod', 'Lightning Aura Rod'), texto: 'Compra tu primer centinela con [[Defender Medal]] (las sueltan los enemigos del evento).' },
      { condicion: B('downedDD2InvasionT1'), texto: 'Supera todas las oleadas del nivel 1.' },
    ],
    combate: 'Los enemigos llegan por ambos lados y van a por el cristal. Coloca los centinelas en los pasillos de entrada y quédate cerca del cristal para rematar lo que pase.',
    desbloquea: 'Medallas de defensor, centinelas y el nivel 2 del evento cuando entres en modo difícil y venzas a un jefe mecánico ({p:dd2t2}).',
    listoCuando: 'Has superado el nivel 1 o lo aplazas (es opcional).',
    completadaCuando: B('downedDD2InvasionT1'),
    conserva: 'Las [[Defender Medal]] que te sobren: el tabernero vende más cosas en los niveles siguientes.',
    avisos: [],
    fuentes: [W('Old One\'s Army'), W('Tavernkeep'), W('Eternia Crystal Stand')],
  },
  {
    id: 'jungla', capitulo: 'prehardmode', titulo: 'La jungla subterránea', tipo: 'exploracion',
    ubicaciones: [Z('jungla_subterranea'), Z('jungla')],
    vida: { min: 260, max: 340, texto: '260–340' },
    donde: 'La jungla, sobre todo su parte subterránea. Está en el lado del mundo opuesto a la Mazmorra.',
    preparate: 'Armadura completa, antídoto contra el veneno si lo tienes, y muchas antorchas: la jungla subterránea es oscura y laberíntica.',
    porClase: {
      cuerpo_a_cuerpo: 'Fabrica la [[Blade of Grass]] con [[Stinger]], [[Jungle Spores]] y [[Vine]]: es una pieza del [[Night\'s Edge]].',
      distancia: 'La [[Boomstick]] (cajas de pesca de la jungla) o la [[Minishark]]; los [[Stinger]] de los avispones vuelan rápido.',
      magia: 'La armadura de la jungla ([[Jungle Hat]], [[Jungle Shirt]] y [[Jungle Pants]]) sube el maná y la probabilidad de crítico mágico.',
      invocacion: 'El [[Snapthorn]] es un látigo de jungla; con la cera de la {p:bee|Abeja reina} harás la armadura de abeja.',
    },
    tareas: [
      { condicion: P('Jungle Spores', 15), texto: 'Recoge al menos 15 [[Jungle Spores]] (plantas brillantes de la jungla subterránea).' },
      { condicion: PA('Anklet of the Wind', 'Ivy Whip'), texto: 'Fabrica la [[Anklet of the Wind]] o el [[Ivy Whip]], un gancho más largo.' },
      { condicion: P('Blade of Grass'), clases: ['cuerpo_a_cuerpo'], texto: 'Fabrica la [[Blade of Grass]].' },
      { condicion: PA('Jungle Hat', 'Jungle Shirt', 'Jungle Pants'), clases: ['magia'], texto: 'Fabrica la armadura de la jungla.' },
      { condicion: P('Snapthorn'), clases: ['invocacion'], texto: 'Fabrica el [[Snapthorn]].' },
      { condicion: M, texto: 'Localiza las colmenas (bloques de colmena y miel): ahí está la larva de la Abeja reina.' },
    ],
    combate: 'Los avispones disparan aguijones venenosos y los [[n:Man Eater]] salen de las paredes. Avanza despacio, ilumina y lleva pociones curativas.',
    desbloquea: 'Materiales de la jungla para armas, accesorios y la armadura de la jungla; acceso a la {p:bee|Abeja reina}.',
    listoCuando: 'Tienes las esporas, el arma o armadura de jungla de tu clase y has localizado una colmena.',
    completadaCuando: P('Jungle Spores', 15),
    conserva: 'Los [[Stinger]], [[Vine]] y [[Jungle Spores]] de sobra: hacen falta para el [[Night\'s Edge]] y otros objetos.',
    avisos: [],
    fuentes: [W('Underground Jungle'), W('Jungle Spores'), W('Blade of Grass'), W('Jungle armor')],
  },
  {
    id: 'bee', capitulo: 'prehardmode', titulo: '[[Queen Bee]]', tipo: 'jefe', jefes: ['Queen Bee'],
    ubicaciones: [Z('colmena'), Z('jungla_subterranea')],
    vida: { min: 300, max: 340, texto: '300–340' },
    donde: 'Una colmena de la jungla subterránea (rompiendo su larva) o cualquier punto de la jungla con su invocador.',
    invocacion: { objeto: 'Abeemination', donde: 'En La jungla.', notas: 'Rompe la larva de una colmena o fabrica la [[Abeemination]] con miel, colmena, un [[Stinger]] y una [[Bottled Honey]].' },
    preparate: 'Arena a cielo abierto en la jungla de la superficie o una colmena vaciada, armadura completa y un arma que golpee bien a un blanco que embiste.',
    porClase: {
      cuerpo_a_cuerpo: 'Un yoyó, la [[Blade of Grass]] o la lanza [[Dark Lance]].',
      distancia: 'La [[Minishark]] o el arco [[Demon Bow]] / [[Tendon Bow]] con flechas de fuego.',
      magia: 'El [[Vilethorn]] o el [[Crimson Rod]], y la [[Space Gun]] si fuiste al meteorito.',
      invocacion: 'Varios esbirros y el látigo; las abejas pequeñas mueren solas contra ellos.',
    },
    tareas: [
      { condicion: ALGUNA(P('Abeemination'), B('downedQueenBee')), texto: 'Fabrica la [[Abeemination]] o localiza una larva.' },
      { condicion: M, texto: 'Si luchas dentro de la colmena, vacíala antes: la miel te frena.' },
      { condicion: B('downedQueenBee'), texto: 'Derrota a la Abeja reina.' },
      { condicion: PA('Bee Keeper', 'Bee Gun', 'The Bee\'s Knees'), texto: 'Recoge su arma: la [[Bee Keeper]] (espada), la [[Bee Gun]] (magia) o la [[The Bee\'s Knees]] (arco).' },
      { condicion: PA('Bee Headgear', 'Bee Breastplate', 'Bee Greaves', 'Hornet Staff'), clases: ['invocacion'], texto: 'Con la [[Bee Wax]] fabrica la armadura de abeja y el [[Hornet Staff]].' },
      { condicion: NPC('Witch Doctor'), texto: 'Recibe al [[Witch Doctor]] en tu pueblo: vende la [[Imbuing Station]] y objetos de invocación.' },
    ],
    combate: 'Alterna embestidas horizontales con fases en las que dispara aguijones y suelta abejas. Corre en sentido contrario a sus embestidas y aprovecha cuando se queda quieta.',
    desbloquea: 'Cera de abeja, el [[Witch Doctor]], la [[Hive Wand]] y, en Experto, el [[Hive Pack]].',
    listoCuando: 'La Abeja reina está vencida y tienes su arma o la armadura de abeja.',
    completadaCuando: B('downedQueenBee'),
    conserva: 'La [[Bee Keeper]] (es parte de la [[Zenith]]) y la [[Bee Wax]] sobrante.',
    avisos: [{ modos: ['clasico', 'viaje'], texto: 'En Clásico no hay [[Hive Pack]] (es de la bolsa de Experto).' }],
    fuentes: [W('Queen Bee'), W('Abeemination'), W('Bee armor'), W('Witch Doctor')],
  },
  {
    id: 'deerclops', capitulo: 'prehardmode', titulo: '[[Deerclops]]', tipo: 'jefe', opcional: true, jefes: ['Deerclops'],
    ubicaciones: [Z('nieve')],
    vida: { min: 300, max: 340, texto: '300–340' },
    donde: 'La Nieve.',
    invocacion: { objeto: 'Deer Thing', donde: 'En el bioma de Nieve.', notas: 'La [[Deer Thing]] se fabrica en un altar demoníaco o carmesí con [[Flinx Fur]], mineral del mal y una [[Lens]].' },
    preparate: 'Armadura completa, arena plana y ancha en la nieve y un arma que ataque a distancia: sus ataques cubren mucho terreno.',
    porClase: {
      cuerpo_a_cuerpo: 'Un yoyó o un arma con proyectil; acercarse sin control es castigado.',
      distancia: 'Arco o arma de fuego con munición mejorada.',
      magia: 'Bastones de gema altos o el [[Vilethorn]] / [[Crimson Rod]].',
      invocacion: 'El [[Flinx Staff]] (con [[Flinx Fur]] de la nieve) y la [[Flinx Fur Coat]].',
    },
    tareas: [
      { condicion: ALGUNA(P('Deer Thing'), B('downedDeerclops')), texto: 'Fabrica la [[Deer Thing]].' },
      { condicion: B('downedDeerclops'), texto: 'Derrota a Deerclops.' },
      { condicion: P('Bone Helm'), opcional: true, texto: 'En Experto, guarda el [[Bone Helm]] de su bolsa.' },
    ],
    combate: 'Lanza fragmentos de hielo por el suelo y oscurece la pantalla con sus gritos. No te quedes en el suelo frente a él y mantén la distancia.',
    desbloquea: 'Armas y objetos de Deerclops; nada obligatorio para la ruta.',
    listoCuando: 'Lo has vencido o lo aplazas (es opcional).',
    completadaCuando: B('downedDeerclops'),
    conserva: 'Nada imprescindible.',
    avisos: [{ modos: ['clasico', 'viaje'], texto: 'En Clásico no hay bolsa del tesoro ni [[Bone Helm]]: deja esa tarea sin marcar.' }],
    fuentes: [W('Deerclops'), W('Deer Thing')],
  },
  {
    id: 'pesca', capitulo: 'prehardmode', titulo: 'Pesca y el Pescador', tipo: 'exploracion', opcional: true,
    ubicaciones: [Z('oceano'), Z('oceano_mazmorra')],
    vida: { min: 200, max: 400, texto: '200–400' },
    donde: 'El Océano (para el [[Angler]]) y cualquier masa de agua grande para pescar.',
    preparate: 'Una caña mejor que la de madera, cebo y, si puedes, la [[Fishing Potion]], la [[Sonar Potion]] y la [[Crate Potion]].',
    porClase: {},
    tareas: [
      { condicion: NPC('Angler'), texto: 'Despierta al [[Sleeping Angler]] en la playa del Océano: se muda a tu pueblo como [[Angler]].' },
      { condicion: PA('Fiberglass Fishing Pole', 'Fisher of Souls', 'Fleshcatcher', 'Golden Fishing Rod', 'Mechanic\'s Rod', 'Sitting Duck\'s Fishing Pole', 'Hotline Fishing Hook'), texto: 'Consigue una caña mejor: la [[Fiberglass Fishing Pole]] (cajas de la jungla), la [[Fisher of Souls]] o la [[Fleshcatcher]] (del mal de tu mundo)…' },
      { condicion: M, texto: 'Completa misiones del Pescador: cada día pide un pez concreto y te recompensa con objetos de pesca y dinero.' },
      { condicion: P('Sonar Potion'), opcional: true, texto: 'Opcional: prepara la [[Sonar Potion]] para ver qué pez ha picado.' },
    ],
    combate: 'Sin combate: solo cuidado con pescar en la superficie durante la Luna de Sangre, que salen enemigos del agua.',
    desbloquea: 'Cajas de pesca con equipo (botas, accesorios y armas de bioma), recompensas del [[Angler]] y peces para pociones. Ver {a:pesca}.',
    listoCuando: 'El Pescador vive en tu pueblo y tienes una caña decente.',
    completadaCuando: NPC('Angler'),
    conserva: 'Las cajas de pesca sin abrir que no necesites ya: en modo difícil dan contenido de modo difícil.',
    avisos: [],
    fuentes: [W('Fishing'), W('Angler'), W('Crates')],
  },
  {
    id: 'skeletron', capitulo: 'prehardmode', titulo: '[[Skeletron]]', tipo: 'jefe', jefes: ['Skeletron'],
    ubicaciones: [PT('mazmorra'), Z('mazmorra')],
    vida: { min: 300, max: 400, texto: '300–400' },
    donde: 'La entrada de la Mazmorra, en uno de los extremos del mundo, de noche.',
    invocacion: { objeto: null, donde: 'Junto al [[Old Man]] que guarda la puerta de la Mazmorra.', notas: 'Habla con él de noche y elige «Maldición». Si mueres o amanece, se escapa y hay que esperar a la siguiente noche.' },
    preparate: 'Tu mejor armadura previa al modo difícil (sombras, carmesí, abeja, jungla o meteorito según tu clase), botas, salto y una plataforma larga frente a la Mazmorra.',
    porClase: {
      cuerpo_a_cuerpo: 'Armadura de las sombras o carmesí y un yoyó o la [[Dark Lance]]; ataca a la cabeza, no a las manos.',
      distancia: 'La [[Minishark]] o un arco con flechas de fuego; munición abundante.',
      magia: 'Armadura de la jungla o de meteorito y la [[Space Gun]] o el [[Vilethorn]].',
      invocacion: 'Armadura de abeja, el [[Hornet Staff]] y un látigo: los avispones persiguen a la cabeza.',
    },
    tareas: [
      { condicion: M, texto: 'Construye una plataforma larga frente a la entrada de la Mazmorra.' },
      { condicion: B('downedBoss3'), texto: 'Habla con el [[Old Man]] por la noche, elige «Maldición» y derrota a Esqueletrón.' },
      { condicion: NPC('Clothier'), texto: 'El [[Old Man]] se convierte en el [[Clothier]] cuando el jefe muere: dale una casa.' },
      { condicion: PA('Bone Glove'), opcional: true, texto: 'En Experto, guarda el [[Bone Glove]] de su bolsa.' },
    ],
    combate: 'Gira sobre sí mismo persiguiéndote: corre en línea y salta sobre él. Las manos se pueden destruir primero para reducir los golpes, pero el daño que cuenta es el de la cabeza.',
    desbloquea: 'Acceso seguro a la Mazmorra ({p:mazmorra}) y al [[Clothier]].',
    listoCuando: 'Esqueletrón está vencido.',
    completadaCuando: B('downedBoss3'),
    conserva: 'El [[Skeletron Hand]] o el [[Book of Skulls]] si caen.',
    avisos: [{ modos: ['clasico', 'viaje'], texto: 'En Clásico no hay bolsa del tesoro ni [[Bone Glove]].' }],
    fuentes: [W('Skeletron'), W('Old Man'), W('The Dungeon')],
  },
  {
    id: 'mazmorra', capitulo: 'prehardmode', titulo: 'Explorar la Mazmorra', tipo: 'exploracion',
    ubicaciones: [PT('mazmorra'), Z('mazmorra')],
    vida: { min: 340, max: 400, texto: '340–400' },
    donde: 'La Mazmorra, en uno de los extremos del mundo.',
    preparate: 'Armadura completa, pociones curativas, muchas antorchas o una [[Shine Potion]] y gancho: la Mazmorra tiene grandes huecos verticales.',
    porClase: {
      cuerpo_a_cuerpo: 'Busca la [[Muramasa]]: es una pieza del [[Night\'s Edge]].',
      distancia: 'Con [[Bone]] y [[Cobweb]] fabricas la armadura de los muertos; la [[Handgun]] de los cofres dorados es la base de la [[Phoenix Blaster]].',
      magia: 'El [[Water Bolt]] está en las estanterías de la Mazmorra; el [[Aqua Scepter]] y el [[Magic Missile]], en los cofres dorados.',
      invocacion: 'El látigo [[Spinal Tap]] se fabrica con [[Bone]] y [[Cobweb]].',
    },
    tareas: [
      { condicion: NPC('Mechanic'), texto: 'Libera al [[Bound Mechanic]] que hay dentro de la Mazmorra: se muda como [[Mechanic]].' },
      { condicion: PA('Muramasa', 'Cobalt Shield', 'Handgun', 'Aqua Scepter', 'Magic Missile', 'Blue Moon', 'Valor', 'Shadow Key'), texto: 'Abre cofres dorados con [[Golden Key]] (las sueltan los enemigos de la Mazmorra) y consigue al menos uno de sus objetos.' },
      { condicion: P('Shadow Key'), texto: 'Consigue la [[Shadow Key]]: abre los cofres de las sombras del Inframundo.' },
      { condicion: P('Water Bolt'), clases: ['magia'], texto: 'Encuentra el [[Water Bolt]] en las estanterías.' },
      { condicion: PA('Necro Helmet', 'Necro Breastplate', 'Necro Greaves'), clases: ['distancia'], texto: 'Fabrica la armadura de los muertos con [[Bone]] y [[Cobweb]].' },
      { condicion: P('Spinal Tap'), clases: ['invocacion'], texto: 'Fabrica el [[Spinal Tap]].' },
    ],
    combate: 'Los esqueletos furiosos y los lanzadores de hechizos aparecen en cuanto entras. Avanza por los pasillos, deja plataformas en los pozos y vuelve a casa a vaciar el inventario a menudo.',
    desbloquea: 'El [[Mechanic]] (cables y mecanismos), el [[Cobalt Shield]] (inmunidad al empuje) y armas clave de las cuatro clases.',
    listoCuando: 'Tienes la llave de las sombras, el objeto de tu clase y el mecánico en el pueblo.',
    completadaCuando: TODAS(NPC('Mechanic'), PA('Muramasa', 'Cobalt Shield', 'Handgun', 'Aqua Scepter', 'Magic Missile', 'Blue Moon', 'Valor', 'Shadow Key')),
    conserva: 'La [[Muramasa]] (para el [[Night\'s Edge]]), el [[Cobalt Shield]] (para el [[Obsidian Shield]]) y la [[Handgun]] (para la [[Phoenix Blaster]]).',
    avisos: [],
    fuentes: [W('The Dungeon'), W('Golden Key'), W('Mechanic'), W('Water Bolt')],
  },
  {
    id: 'antorchas', capitulo: 'prehardmode', titulo: 'El favor del Dios de las antorchas', tipo: 'desafio', opcional: true,
    ubicaciones: [Z('cavernas')],
    vida: { min: 300, max: 400, texto: '300–400' },
    donde: 'Cualquier punto bajo la Superficie.',
    preparate: 'Más de 100 antorchas en el inventario y pociones curativas: las antorchas te atacan durante el evento.',
    porClase: {},
    tareas: [
      { condicion: M, texto: 'Bajo tierra, coloca más de 100 antorchas cerca de ti (por ejemplo, en una pared): empieza el evento del Dios de las antorchas.' },
      { condicion: ALGUNA(P('Torch God\'s Favor'), MEJ('torchGod')), texto: 'Aguanta hasta que termine: recibes el [[Torch God\'s Favor]].' },
      { condicion: MEJ('torchGod'), texto: 'Úsalo: a partir de ahí, las antorchas normales se colocan con la variante de cada bioma y mejoran tu suerte.' },
    ],
    combate: 'Las antorchas lanzan proyectiles hacia ti; muévete y cúrate. Si mueres, se apagan y puedes repetirlo más tarde.',
    desbloquea: 'Antorchas de bioma automáticas (se puede desactivar en el propio objeto de la barra rápida) y mejor suerte.',
    listoCuando: 'Has usado el favor, o lo dejas para más tarde.',
    completadaCuando: MEJ('torchGod'),
    conserva: 'Nada: el favor se consume.',
    avisos: [],
    fuentes: [W('Torch God'), W('Torch God\'s Favor'), W('Luck')],
  },
  {
    id: 'eter', capitulo: 'prehardmode', titulo: 'El Éter y el fulgor', tipo: 'exploracion', opcional: true,
    ubicaciones: [Z('eter')],
    vida: { min: 300, max: 400, texto: '300–400' },
    donde: 'Bajo tierra, en el lado del mundo opuesto a la Mazmorra y cerca del borde (lo genera así el propio juego).',
    preparate: 'Gancho y plataformas: el lago de fulgor está en una cueva profunda. Lleva objetos que quieras transformar.',
    porClase: {},
    tareas: [
      { condicion: M, texto: 'Encuentra el lago del Éter: un líquido brillante de colores llamado fulgor.' },
      { condicion: M, texto: 'Prueba a tirar un objeto al fulgor: muchos se transforman en otro, y lo fabricado vuelve a sus ingredientes.' },
      { condicion: ALGUNA(MEJ('aegisCrystal'), MEJ('arcaneCrystal'), MEJ('galaxyPearl'), MEJ('gummyWorm'), MEJ('ambrosia')), texto: 'Usa una mejora permanente del fulgor: un [[Life Crystal]] se convierte en [[Vital Crystal]], un [[Mana Crystal]] en [[Arcane Crystal]], una [[Pink Pearl]] en [[Galaxy Pearl]], un [[o:Gold Worm]] en [[Gummy Worm]] y la fruta en [[Ambrosia]].' },
    ],
    combate: 'Si te bañas en el fulgor atraviesas los bloques hacia abajo: sal antes de hundirte demasiado.',
    desbloquea: 'Transmutaciones, deshacer recetas y mejoras permanentes. Ver {a:eter}.',
    listoCuando: 'Conoces dónde está y has usado al menos una mejora permanente, o lo dejas para más tarde.',
    completadaCuando: null,
    conserva: 'Los [[Life Crystal]] y [[Mana Crystal]] de sobra: en el fulgor son mejoras permanentes.',
    avisos: [],
    fuentes: [W('Shimmer'), W('Aether'), W('Vital Crystal')],
  },
  {
    id: 'inframundo', capitulo: 'prehardmode', titulo: 'El Inframundo: piedra infernal y armadura fundida', tipo: 'exploracion',
    ubicaciones: [Z('inframundo')],
    vida: { min: 340, max: 400, texto: '340–400' },
    donde: 'El Inframundo, al fondo del mundo.',
    preparate: 'La [[Nightmare Pickaxe]] o la [[Deathbringer Pickaxe]], [[Obsidian Skin Potion]] y un pozo vertical para bajar y subir rápido (el «ascensor al infierno»).',
    porClase: {
      cuerpo_a_cuerpo: 'Con [[Hellstone Bar]] fabricas la armadura fundida ([[Molten Helmet]], [[Molten Breastplate]] y [[Molten Greaves]]) y el [[Volcano]].',
      distancia: 'La [[Phoenix Blaster]] ([[Handgun]] + barras infernales) o el arco [[Molten Fury]].',
      magia: 'El [[Flower of Fire]] sale de los cofres de las sombras; la [[Demon Scythe]] la sueltan los demonios.',
      invocacion: 'El [[Imp Staff]] se fabrica con barras infernales: un esbirro que dispara fuego.',
    },
    tareas: [
      { condicion: PA('Hellstone Bar', 'Molten Pickaxe', 'Molten Helmet', 'Molten Breastplate', 'Molten Greaves'), texto: 'Pica [[Hellstone]] y fúndela en la [[Hellforge]] (la encuentras en las casas en ruinas) con [[Obsidian]].' },
      { condicion: P('Molten Pickaxe'), texto: 'Fabrica la [[Molten Pickaxe]]: necesitarás un pico así para entrar con buen pie en el modo difícil.' },
      { condicion: PA('Molten Helmet', 'Molten Breastplate', 'Molten Greaves'), clases: ['cuerpo_a_cuerpo'], texto: 'Fabrica la armadura fundida.' },
      { condicion: P('Imp Staff'), clases: ['invocacion'], texto: 'Fabrica el [[Imp Staff]].' },
      { condicion: M, texto: 'Abre los cofres de las sombras de las casas en ruinas con la [[Shadow Key]].' },
    ],
    combate: 'Los demonios lanzan guadañas a través de los bloques y los murciélagos de lava queman. No piques sobre la lava sin la poción de piel obsidiana.',
    desbloquea: 'El equipo de la última etapa previa al modo difícil y la posibilidad de enfrentarte al {p:wall|Muro carnoso}.',
    listoCuando: 'Tienes la [[Molten Pickaxe]] y la armadura o el arma de tu clase hecha con piedra infernal.',
    completadaCuando: P('Molten Pickaxe'),
    conserva: 'Barras infernales de sobra y la [[Hellforge]]: la necesitarás para la forja de modo difícil.',
    avisos: [],
    fuentes: [W('The Underworld'), W('Hellstone'), W('Molten armor'), W('Hellforge')],
  },
  {
    id: 'armapre', capitulo: 'prehardmode', titulo: 'Tu mejor arma antes del Muro', tipo: 'preparacion',
    ubicaciones: [PT('spawn')],
    vida: { min: 380, max: 400, texto: '380–400' },
    donde: 'Tu base: todo se fabrica con lo que ya has reunido.',
    preparate: 'Los componentes de tu clase que has ido guardando y el [[Tinkerer\'s Workshop]] para los accesorios.',
    porClase: {
      cuerpo_a_cuerpo: 'Combina [[Light\'s Bane]] o [[Blood Butcherer]], [[Muramasa]], [[Blade of Grass]] y [[Volcano]] en el [[Night\'s Edge]].',
      distancia: 'La [[Phoenix Blaster]] o la [[Minishark]] con munición mejorada, y la [[Star Cannon]] si tienes estrellas.',
      magia: 'El [[Water Bolt]], la [[Demon Scythe]] o el [[Flower of Fire]], con 200 de maná.',
      invocacion: 'El [[Imp Staff]] o el [[Hornet Staff]], la armadura de abeja u obsidiana y un buen látigo.',
    },
    tareas: [
      { condicion: P('Night\'s Edge'), clases: ['cuerpo_a_cuerpo'], texto: 'Fabrica el [[Night\'s Edge]] en un altar demoníaco o carmesí.' },
      { condicion: PA('Phoenix Blaster', 'Minishark', 'Star Cannon', 'Molten Fury'), clases: ['distancia'], texto: 'Ten un arma de distancia final: [[Phoenix Blaster]], [[Minishark]], [[Star Cannon]] o [[Molten Fury]].' },
      { condicion: MANA(200), clases: ['magia'], texto: 'Llega a 200 de maná con [[Mana Crystal]].' },
      { condicion: PA('Imp Staff', 'Hornet Staff'), clases: ['invocacion'], texto: 'Ten el [[Imp Staff]] o el [[Hornet Staff]].' },
      { condicion: PA('Obsidian Shield', 'Obsidian Skull'), texto: 'Fabrica el [[Obsidian Shield]] ([[Cobalt Shield]] + [[Obsidian Skull]]): inmunidad al empuje y a los bloques que queman.' },
      { condicion: VIDA(400), texto: 'Llega a 400 de vida con [[Life Crystal]] (15 en total).' },
    ],
    combate: 'Prueba tu equipo contra enemigos del Inframundo antes del Muro: si no aguantas una casa en ruinas, aún no estás listo.',
    desbloquea: 'Nada nuevo: es la revisión antes del Muro.',
    listoCuando: 'Tienes 400 de vida, el arma final de tu clase y el escudo de obsidiana.',
    completadaCuando: VIDA(400),
    conserva: 'El [[Night\'s Edge]] (se mejora en modo difícil al [[True Night\'s Edge]] y forma parte de la [[Terra Blade]]).',
    avisos: [],
    fuentes: [W('Night\'s Edge'), W('Phoenix Blaster'), W('Guide:Class setups')],
  },
  {
    id: 'wall', capitulo: 'prehardmode', titulo: '[[Wall of Flesh]]', tipo: 'jefe', jefes: ['Wall of Flesh'],
    ubicaciones: [Z('inframundo')],
    vida: { min: 400, max: 400, texto: '400' },
    donde: 'El Inframundo. Aparece en un borde de la pantalla y avanza hacia el otro.',
    invocacion: { objeto: 'Guide Voodoo Doll', donde: 'Tírala a la lava del Inframundo mientras el [[Guide]] está vivo.', notas: 'La suelta el [[Voodoo Demon]] (un demonio que lleva el muñeco en las manos).' },
    preparate: 'Un puente largo y recto de lado a lado del Inframundo (o al menos 600 casillas), 400 de vida, tu arma final de antes del modo difícil y pociones ([[Ironskin Potion]], [[Regeneration Potion]], [[Swiftness Potion]]).',
    porClase: {
      cuerpo_a_cuerpo: 'El [[Night\'s Edge]] o un yoyó como el [[Cascade]]; armadura fundida.',
      distancia: 'La [[Phoenix Blaster]] o la [[Minishark]] con munición mejor, y la armadura de los muertos o de meteorito.',
      magia: 'La [[Demon Scythe]] o el [[Water Bolt]], armadura de la jungla o de meteorito y pociones de maná.',
      invocacion: 'El [[Imp Staff]] y un látigo; corre sin parar y deja que los esbirros peguen.',
    },
    tareas: [
      { condicion: M, texto: 'Construye el puente sobre la lava y ponle antorchas o algo de luz.' },
      { condicion: ALGUNA(NPC('Guide'), B('hardMode')), texto: 'Comprueba que el [[Guide]] está vivo en tu pueblo.' },
      { condicion: ALGUNA(P('Guide Voodoo Doll'), B('hardMode')), texto: 'Consigue la [[Guide Voodoo Doll]] matando [[Voodoo Demon]].' },
      { condicion: B('hardMode'), texto: 'Derrota al Muro carnoso: el mundo pasa a modo difícil.' },
      { condicion: MEJ('demonHeart'), texto: 'En Experto, usa el [[Demon Heart]] de la bolsa: te da un hueco de accesorio más para siempre.' },
    ],
    combate: 'Avanza hacia ti sin parar: corre en sentido contrario por el puente mientras atacas. Mata las sanguijuelas que suelta y no dejes que te atrape la lengua (te arrastra si te alejas demasiado).',
    desbloquea: 'El modo difícil: nuevos biomas, minerales, enemigos y el [[Pwnhammer]] para romper altares. Ver {p:hardstart}.',
    listoCuando: 'El mundo está en modo difícil.',
    completadaCuando: B('hardMode'),
    conserva: 'El [[Pwnhammer]] y el emblema que suelta.',
    avisos: [
      { modos: ['clasico', 'viaje'], texto: 'En Clásico no hay [[Demon Heart]]: tendrás un hueco de accesorio menos. Marca esa tarea a mano.' },
      { modos: ['experto', 'maestro'], texto: 'Al entrar en modo difícil se genera una franja de Lo Sagrado y otra de la maldad de tu mundo: la expansión empieza ya.' },
    ],
    fuentes: [W('Wall of Flesh'), W('Guide Voodoo Doll'), W('Hardmode')],
  },
];

module.exports = { paradas };
