// Guia v2 (F1, 02-oct-2026): ruta vanilla, capitulos «Modo difícil», «Tras Plantera» y «El Señor
// de la Luna y después». Mismo marcado que paradas-1.js. Datos verificados en el decompilado de
// tModLoader 1.4.4.9 (recetas/botin/tiendas: tabla de referencias generada del codigo real):
//   - Jefes mecanicos naturales: cada noche 1/10 con altares rotos y algun mecanico pendiente
//     (Main.cs ~82999).
//   - Invasion pirata natural: modo dificil + altar roto, 1/30 diario (1/60 tras vencerla)
//     (Main.cs ~83224).
//   - Crisopa prismatica (Emperatriz de la luz): tras Plantera, de noche hasta medianoche
//     (NPC.cs ~89524). Terraprisma solo si la vence de dia (EmpressOfLightIsGenuinelyEnraged).
//   - Escudo de las columnas: 100 bajas, 50 tras vencer al Señor de la Luna (NPC.cs ~953/1553).
'use strict';
const { B, P, PA, EQ, NPC, VIDA, FRUTAS, MANA, DEF, MEJ, TODAS, ALGUNA, M, Z, PT, W } = require('./ayudas.js');

const ALAS_TEMPRANAS = ['Angel Wings', 'Demon Wings', 'Fairy Wings', 'Frozen Wings', 'Fledgling Wings', 'Harpy Wings', 'Leaf Wings', 'Bat Wings', 'Bee Wings', 'Butterfly Wings', 'Flame Wings', 'Spectre Wings', 'Beetle Wings', 'Hoverboard', 'Spooky Wings', 'Tattered Fairy Wings', 'Festive Wings', 'Steampunk Wings', 'Fishron Wings', 'Empress Wings', 'Betsy\'s Wings'];

const paradas = [
  // =========================================================== Modo difícil
  {
    id: 'hardstart', capitulo: 'hardmode', titulo: 'Primeros pasos en modo difícil', tipo: 'preparacion',
    ubicaciones: [Z('altares'), Z('cavernas')],
    vida: { min: 400, max: 400, texto: '400' },
    donde: 'Las Cavernas, donde están los altares demoníacos o carmesíes y los minerales nuevos.',
    preparate: 'El [[Pwnhammer]] del Muro, la [[Molten Pickaxe]] y tu equipo previo: los enemigos de las cavernas son ahora mucho más duros, así que avanza con cuidado.',
    porClase: {
      cuerpo_a_cuerpo: 'La [[Breaker Blade]] del Muro si te tocó; si no, el [[Night\'s Edge]] hasta tener armas de cobalto o paladio.',
      distancia: 'La [[Clockwork Assault Rifle]] del Muro o la [[Phoenix Blaster]]; más adelante, el [[Daedalus Stormbow]].',
      magia: 'El [[Laser Rifle]] del Muro, o el [[Crystal Storm]] / [[Cursed Flames]] / [[Golden Shower]] en cuanto tengas almas.',
      invocacion: 'El [[Firecracker]] del Muro y la armadura de araña ([[Spider Mask]], [[Spider Breastplate]], [[Spider Greaves]]) con [[Spider Fang]] de los nidos de araña.',
    },
    tareas: [
      { condicion: M, texto: 'Rompe altares demoníacos o carmesíes con el [[Pwnhammer]]: cada uno siembra minerales nuevos en el mundo (y suelta espectros).' },
      { condicion: PA('Cobalt Bar', 'Palladium Bar', 'Mythril Bar', 'Orichalcum Bar', 'Adamantite Bar', 'Titanium Bar'), texto: 'Pica cobalto o paladio y funde las primeras barras de modo difícil.' },
      { condicion: PA('Mythril Anvil', 'Orichalcum Anvil'), texto: 'Fabrica el [[Mythril Anvil]] o el [[Orichalcum Anvil]]: muchas recetas de modo difícil lo exigen.' },
      { condicion: PA('Adamantite Forge', 'Titanium Forge'), texto: 'Con adamantita o titanio y tu [[Hellforge]], fabrica la [[Adamantite Forge]] o la [[Titanium Forge]].' },
      { condicion: PA(...ALAS_TEMPRANAS), texto: 'Consigue unas alas: las [[Angel Wings]] o las [[Demon Wings]] usan [[Soul of Flight]] de los guivernos del Cielo.' },
      { condicion: NPC('Wizard'), texto: 'Libera al [[Bound Wizard]] en las Cavernas: se muda como [[Wizard]] y vende la [[Crystal Ball]].' },
    ],
    combate: 'Los mímicos se disfrazan de cofre y los fantasmas y espectros atraviesan paredes. No abras cofres en una sala cerrada sin salida.',
    desbloquea: 'Minerales de modo difícil, armaduras y armas nuevas de las cuatro clases, almas de luz y de noche ({p:sagrado}) y, con tres altares rotos, todos los niveles de mineral.',
    listoCuando: 'Tienes armadura de mithril u oricalco (o mejor), alas y el yunque de modo difícil.',
    completadaCuando: TODAS(PA('Mythril Anvil', 'Orichalcum Anvil'), PA(...ALAS_TEMPRANAS)),
    conserva: 'Tu [[Hellforge]] (se gasta en la forja de adamantita) y el emblema del Muro (base del [[Avenger Emblem]]).',
    avisos: [{ modos: ['clasico', 'viaje', 'experto', 'maestro'], texto: 'Los minerales que salen de cada altar dependen de lo que tu mundo eligió al entrar en modo difícil: puedes tener cobalto o paladio, mithril u oricalco y adamantita o titanio, nunca los dos de cada pareja (salvo semillas especiales).' }],
    fuentes: [W('Hardmode'), W('Pwnhammer'), W('Altars'), W('Wings')],
  },
  {
    id: 'sagrado', capitulo: 'hardmode', titulo: 'Lo Sagrado y las almas', tipo: 'exploracion',
    ubicaciones: [Z('sagrado'), Z('corrupcion', 'corrupcion'), Z('carmesi', 'carmesi')],
    vida: { min: 400, max: 440, texto: '400–440' },
    donde: 'Lo Sagrado y la maldad de tu mundo, sobre todo sus capas subterráneas.',
    preparate: 'Tu armadura de modo difícil y alas. Para frenar la expansión, compra [[Purification Powder]] a la [[n:Dryad]].',
    porClase: {
      cuerpo_a_cuerpo: 'Con almas fabricas armas como la [[Light Disc]] o los mejores yoyós; el [[Cool Whip]] es de invocación.',
      distancia: 'Mata mímicos de Lo Sagrado para el [[Daedalus Stormbow]] (hace falta una [[Key of Light]]).',
      magia: 'El [[Crystal Storm]] (fragmentos de cristal) o el [[Cursed Flames]] / [[Golden Shower]] (con un [[Spell Tome]] y 15 almas).',
      invocacion: 'La armadura de araña y el [[Spider Staff]]; con almas, el [[Cool Whip]].',
    },
    tareas: [
      { condicion: P('Soul of Light', 15), texto: 'Reúne al menos 15 [[Soul of Light]] en Lo Sagrado subterráneo.' },
      { condicion: P('Soul of Night', 15), texto: 'Reúne al menos 15 [[Soul of Night]] en la maldad subterránea.' },
      { condicion: PA('Crystal Shard', 'Unicorn Horn', 'Pixie Dust'), texto: 'Recoge materiales sagrados: [[Crystal Shard]], [[Unicorn Horn]] o [[Pixie Dust]].' },
      { condicion: PA('Daedalus Stormbow', 'Flesh Knuckles', 'Fetid Baghnakhs', 'Chain Guillotines', 'Dart Rifle', 'Dart Pistol', 'Putrid Scent', 'Clinger Staff', 'Life Drain', 'Crystal Vile Shard', 'Illuminant Hook', 'Tendon Hook', 'Worm Hook'), opcional: true, texto: 'Opcional: con una [[Key of Light]] o [[Key of Night]] en un cofre vacío, invoca un mímico de bioma y consigue su objeto.' },
      { condicion: M, texto: 'Decide cómo frenar la expansión: zanjas de tres casillas, [[Purification Powder]] o, más tarde, el [[Clentaminator]] del [[Steampunker]].' },
    ],
    combate: 'Los enemigos sagrados y malditos pegan fuerte y algunos atraviesan bloques. Lucha en una zona abierta y no bajes a las capas profundas sin alas.',
    desbloquea: 'Almas para los invocadores mecánicos, el [[Mythril Anvil]] y casi todas las armas de modo difícil temprano.',
    listoCuando: 'Tienes almas de luz y de noche suficientes para tus invocadores y tu arma.',
    completadaCuando: TODAS(P('Soul of Light', 15), P('Soul of Night', 15)),
    conserva: 'Las almas que te sobren: los invocadores mecánicos piden de las dos.',
    avisos: [],
    fuentes: [W('The Hallow'), W('Soul of Light'), W('Soul of Night'), W('Biome Mimic')],
  },
  {
    id: 'queenslime', capitulo: 'hardmode', titulo: '[[Queen Slime]]', tipo: 'jefe', opcional: true, jefes: ['Queen Slime'],
    ubicaciones: [Z('sagrado')],
    vida: { min: 400, max: 440, texto: '400–440' },
    donde: 'Cualquier sitio, pero lo normal es Lo Sagrado: su invocador sale del subsuelo sagrado.',
    invocacion: { objeto: 'Gelatin Crystal', donde: 'En Lo Sagrado.', notas: 'El [[Gelatin Crystal]] crece en las cuevas de Lo Sagrado subterráneo; se recoge con el pico.' },
    preparate: 'Alas, armadura de modo difícil y una plataforma larga y alta: salta, se teletransporta y en su segunda fase vuela.',
    porClase: {
      cuerpo_a_cuerpo: 'Un yoyó de modo difícil o armas de cobalto/paladio con alcance.',
      distancia: 'El [[Daedalus Stormbow]] o la [[Clockwork Assault Rifle]].',
      magia: 'El [[Crystal Storm]] o el [[Golden Shower]].',
      invocacion: 'El [[Spider Staff]]; su arma, el [[Blade Staff]], es de invocación.',
    },
    tareas: [
      { condicion: ALGUNA(P('Gelatin Crystal'), B('downedQueenSlime')), texto: 'Consigue un [[Gelatin Crystal]].' },
      { condicion: B('downedQueenSlime'), texto: 'Derrota a la Reina slime.' },
      { condicion: PA('Blade Staff', 'Gelatinous Pillion', 'Volatile Gelatin'), opcional: true, texto: 'Recoge el [[Blade Staff]] o la [[Gelatinous Pillion]] (montura).' },
    ],
    combate: 'En la primera fase salta y suelta slimes de cristal; en la segunda vuela y dispara en abanico. Esquiva en horizontal con alas y no te quedes debajo.',
    desbloquea: 'El [[Blade Staff]], la montura y, en Experto, la [[Volatile Gelatin]].',
    listoCuando: 'La has vencido o la aplazas (es opcional).',
    completadaCuando: B('downedQueenSlime'),
    conserva: 'El [[Blade Staff]] si juegas invocación.',
    avisos: [{ modos: ['clasico', 'viaje'], texto: 'En Clásico no hay [[Volatile Gelatin]] (bolsa de Experto).' }],
    fuentes: [W('Queen Slime'), W('Gelatin Crystal')],
  },
  {
    id: 'pirates', capitulo: 'hardmode', titulo: 'Invasión pirata', tipo: 'evento', opcional: true,
    ubicaciones: [PT('spawn'), Z('oceano')],
    vida: { min: 400, max: 440, texto: '400–440' },
    donde: 'Llega a tu base desde el lado del Océano más cercano.',
    invocacion: { objeto: 'Pirate Map', donde: 'Úsalo cerca del Océano.', notas: 'Llega sola (1 de cada 30 días) en modo difícil tras romper un altar. El [[Pirate Map]] lo suelta cualquier enemigo cerca del Océano en modo difícil.' },
    preparate: 'Armadura de modo difícil, alas y un arma de área: llegan muchos enemigos a la vez y el [[Flying Dutchman]] dispara cañones.',
    porClase: {},
    tareas: [
      { condicion: B('downedPirates'), texto: 'Derrota la Invasión pirata.' },
      { condicion: NPC('Pirate'), texto: 'Recibe al [[Pirate]] en tu pueblo: vende el [[Cannon]] y munición.' },
      { condicion: PA('Lucky Coin', 'Gold Ring', 'Discount Card', 'Pirate Staff', 'Coin Gun'), opcional: true, texto: 'Opcional: consigue alguno de sus objetos raros ([[Lucky Coin]], [[Discount Card]], [[Gold Ring]], [[Pirate Staff]]…).' },
    ],
    combate: 'Elimina primero a los tiradores y al [[Pirate Captain]]; el barco volador se ataca por sus cañones.',
    desbloquea: 'El [[Pirate]] como vecino y objetos de dinero que, combinados, dan el [[Greedy Ring]].',
    listoCuando: 'La has superado o la aplazas (es opcional).',
    completadaCuando: B('downedPirates'),
    conserva: 'Los anillos y la moneda si quieres el [[Greedy Ring]].',
    avisos: [],
    fuentes: [W('Pirate Invasion'), W('Pirate Map'), W('Pirate')],
  },
  {
    id: 'frostlegion', capitulo: 'hardmode', titulo: 'Legión de escarcha', tipo: 'evento', opcional: true,
    ubicaciones: [PT('spawn')],
    vida: { min: 400, max: 440, texto: '400–440' },
    donde: 'Tu base, en la Superficie.',
    invocacion: { objeto: 'Snow Globe', donde: 'En la Superficie.', notas: 'La [[Snow Globe]] sale de los [[Present]] en modo difícil (los regalos caen de cualquier enemigo durante Navidad).' },
    preparate: 'Arma de área y casas protegidas: los muñecos de nieve atacan en grupo.',
    porClase: {},
    tareas: [
      { condicion: ALGUNA(P('Snow Globe'), B('downedFrost')), texto: 'Consigue una [[Snow Globe]].' },
      { condicion: B('downedFrost'), texto: 'Derrota a la Legión de escarcha.' },
      { condicion: NPC('Santa Claus'), texto: 'Recibe a [[Santa Claus]], que se muda en temporada de Navidad.' },
    ],
    combate: 'Muchos enemigos terrestres: lucha desde arriba con un arma que atraviese.',
    desbloquea: '[[Santa Claus]] como vecino durante la Navidad.',
    listoCuando: 'La has superado o la aplazas (es opcional).',
    completadaCuando: B('downedFrost'),
    conserva: 'Nada imprescindible.',
    avisos: [],
    fuentes: [W('Frost Legion'), W('Snow Globe'), W('Christmas')],
  },
  {
    id: 'mech1', capitulo: 'hardmode', titulo: '[[n:The Destroyer]]', tipo: 'jefe', jefes: ['n:The Destroyer'],
    ubicaciones: [Z('superficie')],
    vida: { min: 400, max: 460, texto: '400–460' },
    donde: 'Superficie, de noche.',
    invocacion: { objeto: 'Mechanical Worm', donde: 'De noche.', notas: 'Se fabrica en el [[Mythril Anvil]] o [[Orichalcum Anvil]] con trozos o vértebras, barras de hierro y [[Soul of Night]]. También puede aparecer solo (1 de cada 10 noches mientras falte algún mecánico).' },
    preparate: 'Una plataforma muy larga a cierta altura, alas, armadura de mithril u oricalco o mejor y un arma que golpee a muchos segmentos.',
    porClase: {
      cuerpo_a_cuerpo: 'Un yoyó o una espada que atraviese; la [[Light Disc]] rebota entre segmentos.',
      distancia: 'El [[Daedalus Stormbow]] con [[Holy Arrow]] o [[Unholy Arrow]] destroza al gusano.',
      magia: 'El [[Crystal Storm]] o el [[Cursed Flames]]; los proyectiles que atraviesan rinden mucho.',
      invocacion: 'El [[Spider Staff]] y un látigo; los esbirros persiguen solos los segmentos.',
    },
    tareas: [
      { condicion: ALGUNA(P('Mechanical Worm'), B('downedMechBoss1')), texto: 'Fabrica el [[Mechanical Worm]].' },
      { condicion: M, texto: 'Construye la arena: plataformas largas en varias alturas.' },
      { condicion: B('downedMechBoss1'), texto: 'Derrota al Destructor antes de que amanezca.' },
      { condicion: P('Soul of Might'), texto: 'Recoge las [[Soul of Might]].' },
    ],
    combate: 'Sus segmentos disparan láseres y sueltan sondas. Vuela por encima y en círculos amplios; no te quedes en su trayectoria cuando sube desde el suelo.',
    desbloquea: 'Almas de poder, barras sagradas, las [[Life Fruit]] en la jungla subterránea, el [[Steampunker]] y el nivel 2 del Ejército del Antiguo.',
    listoCuando: 'El Destructor está vencido.',
    completadaCuando: B('downedMechBoss1'),
    conserva: 'Las [[Hallowed Bar]] y las almas de poder.',
    avisos: [{ modos: ['experto', 'maestro'], texto: 'En Experto, su bolsa da la [[Mechanical Wagon Piece]], una de las tres piezas del [[Minecart Upgrade Kit]].' }],
    fuentes: [W('The Destroyer'), W('Mechanical Worm')],
  },
  {
    id: 'mech2', capitulo: 'hardmode', titulo: '[[Retinazer]] y [[Spazmatism]]', tipo: 'jefe', jefes: ['Retinazer', 'Spazmatism'],
    ubicaciones: [Z('superficie')],
    vida: { min: 420, max: 480, texto: '420–480' },
    donde: 'Superficie, de noche.',
    invocacion: { objeto: 'Mechanical Eye', donde: 'De noche.', notas: 'Se fabrica en el yunque de modo difícil con 3 [[Lens]], barras de hierro y [[Soul of Light]].' },
    preparate: 'Alas, botas y una arena abierta: los Gemelos te persiguen por el aire. Un arma que siga a su objetivo ayuda mucho.',
    porClase: {
      cuerpo_a_cuerpo: 'Un yoyó o armas con proyectil; la [[Light Disc]] también va bien.',
      distancia: 'La [[Megashark]] o el [[Daedalus Stormbow]] con munición perforante.',
      magia: 'El [[Crystal Storm]] o el [[Magical Harp]].',
      invocacion: 'El [[Spider Staff]] o el [[Blade Staff]].',
    },
    tareas: [
      { condicion: ALGUNA(P('Mechanical Eye'), B('downedMechBoss2')), texto: 'Fabrica el [[Mechanical Eye]].' },
      { condicion: B('downedMechBoss2'), texto: 'Derrota a los Gemelos antes de que amanezca.' },
      { condicion: P('Soul of Sight'), texto: 'Recoge las [[Soul of Sight]].' },
    ],
    combate: 'Concentra el daño en uno de los dos: [[Retinazer]] dispara láseres a distancia y [[Spazmatism]] embiste y lanza fuego. En su segunda fase son más rápidos.',
    desbloquea: 'Almas de visión para el [[Optic Staff]], la [[Megashark]] y las herramientas sagradas.',
    listoCuando: 'Los Gemelos están vencidos.',
    completadaCuando: B('downedMechBoss2'),
    conserva: 'Las almas de visión y la [[Black Lens]] si cae (para el [[Optic Staff]]).',
    avisos: [{ modos: ['experto', 'maestro'], texto: 'En Experto, su bolsa da la [[Mechanical Wheel Piece]] del [[Minecart Upgrade Kit]].' }],
    fuentes: [W('The Twins'), W('Mechanical Eye')],
  },
  {
    id: 'mech3', capitulo: 'hardmode', titulo: '[[Skeletron Prime]]', tipo: 'jefe', jefes: ['Skeletron Prime'],
    ubicaciones: [Z('superficie')],
    vida: { min: 440, max: 500, texto: '440–500' },
    donde: 'Superficie, de noche.',
    invocacion: { objeto: 'Mechanical Skull', donde: 'De noche.', notas: 'Se fabrica en el yunque de modo difícil con 30 [[Bone]], barras de hierro y almas de luz y de noche.' },
    preparate: 'Alas, la mejor armadura que tengas y una arena muy ancha: sus cuatro brazos cubren mucho espacio.',
    porClase: {
      cuerpo_a_cuerpo: 'Armas con alcance; ataca la cabeza y no te quedes entre los brazos.',
      distancia: 'La [[Megashark]] o el [[Daedalus Stormbow]].',
      magia: 'El [[Crystal Storm]] o el [[Rainbow Rod]].',
      invocacion: 'El [[Optic Staff]] (si ya venciste a los Gemelos) y un látigo.',
    },
    tareas: [
      { condicion: ALGUNA(P('Mechanical Skull'), B('downedMechBoss3')), texto: 'Fabrica el [[Mechanical Skull]].' },
      { condicion: B('downedMechBoss3'), texto: 'Derrota a Esqueletrón mayor.' },
      { condicion: P('Soul of Fright'), texto: 'Recoge las [[Soul of Fright]].' },
      { condicion: B('downedMechBossAll'), texto: 'Con los tres mecánicos vencidos aparecen los bulbos de Plantera en la jungla subterránea.' },
    ],
    combate: 'Gira y embiste como el primer Esqueletrón, pero sus brazos (sierra, vicio, cañón y láser) atacan por separado. Destruir algún brazo primero simplifica la pelea.',
    desbloquea: 'Almas de terror, los bulbos de Plantera (con los tres mecánicos) y el [[Avenger Emblem]] con las tres almas.',
    listoCuando: 'Los tres jefes mecánicos están vencidos.',
    completadaCuando: B('downedMechBoss3'),
    conserva: 'Las almas de poder, visión y terror: el [[True Night\'s Edge]], las herramientas sagradas y muchos accesorios las piden.',
    avisos: [{ modos: ['experto', 'maestro'], texto: 'En Experto, su bolsa da la [[Mechanical Battery Piece]]: con las tres piezas fabricas el [[Minecart Upgrade Kit]] ({p:mejoras}).' }],
    fuentes: [W('Skeletron Prime'), W('Mechanical Skull')],
  },
  {
    id: 'frutas', capitulo: 'hardmode', titulo: 'Frutas de vida y herramientas sagradas', tipo: 'preparacion',
    ubicaciones: [Z('jungla_subterranea')],
    vida: { min: 500, max: 500, trasMejora: true, texto: '500 tras las 20 frutas' },
    donde: 'La jungla subterránea (frutas de vida) y tu base (forja).',
    preparate: 'Alas, armadura sagrada o de nivel similar y el pico de modo difícil más alto que tengas.',
    porClase: {
      cuerpo_a_cuerpo: 'Armadura sagrada con el [[Hallowed Mask]] y la [[Excalibur]] o el [[True Night\'s Edge]].',
      distancia: 'Armadura sagrada con el [[Hallowed Helmet]] y la [[Megashark]].',
      magia: 'Armadura sagrada con el [[Hallowed Headgear]] y el [[Rainbow Rod]] o el [[Magical Harp]].',
      invocacion: 'Armadura sagrada con el [[Hallowed Hood]] y el [[Optic Staff]].',
    },
    tareas: [
      { condicion: FRUTAS(20), texto: 'Usa 20 [[Life Fruit]] (bulbos amarillos de la jungla subterránea, tras el primer mecánico): llegas a 500 de vida.' },
      { condicion: PA('Pickaxe Axe', 'Drax'), texto: 'Fabrica la [[Pickaxe Axe]] o el [[Drax]]: son los primeros picos que pican el [[Chlorophyte Ore]].' },
      { condicion: PA('Hallowed Plate Mail', 'Hallowed Greaves', 'Ancient Hallowed Plate Mail'), texto: 'Fabrica la armadura sagrada (cuerpo y piernas valen para todas las clases; el casco, el de la tuya).' },
      { condicion: P('Avenger Emblem'), texto: 'Mejora el emblema del Muro al [[Avenger Emblem]].' },
      { condicion: NPC('Steampunker'), texto: 'Recibe al [[Steampunker]]: vende el [[Clentaminator]] y las soluciones para limpiar biomas.' },
    ],
    combate: 'La jungla subterránea de modo difícil es peligrosa: avispones gigantes, plantas que te atrapan y arañas. Ilumínala y lleva alas para escapar.',
    desbloquea: 'La clorofita (con el nuevo pico) y la ruta hacia Plantera.',
    listoCuando: 'Tienes 500 de vida, armadura sagrada y un pico que pique clorofita.',
    completadaCuando: TODAS(FRUTAS(20), PA('Pickaxe Axe', 'Drax')),
    conserva: 'Las barras sagradas sobrantes: la [[Excalibur]] lleva a la [[True Excalibur]] y a la [[Terra Blade]].',
    avisos: [],
    fuentes: [W('Life Fruit'), W('Hallowed armor'), W('Pickaxe Axe'), W('Chlorophyte Ore')],
  },
  {
    id: 'dd2t2', capitulo: 'hardmode', titulo: 'Ejército del Antiguo (nivel 2)', tipo: 'evento', opcional: true,
    ubicaciones: [PT('spawn')],
    vida: { min: 440, max: 500, texto: '440–500' },
    donde: 'Donde tengas el [[Eternia Crystal Stand]].',
    invocacion: { objeto: 'Eternia Crystal', donde: 'Sobre el soporte.', notas: 'El nivel 2 se activa en modo difícil tras vencer a cualquier jefe mecánico.' },
    preparate: 'Centinelas de nivel 2 del [[n:Tavernkeep]], armadura de modo difícil y alas. Llegan ogros: pegan muy fuerte.',
    porClase: {},
    tareas: [
      { condicion: B('downedMechBossAny'), texto: 'Vence a un jefe mecánico para desbloquear el nivel 2.' },
      { condicion: B('downedDD2InvasionT2'), texto: 'Supera todas las oleadas del nivel 2.' },
      { condicion: PA('Squire\'s Great Helm', 'Monk\'s Bushy Brow Bald Cap', 'Huntress\'s Wig', 'Apprentice\'s Hat'), opcional: true, texto: 'Opcional: compra con medallas una armadura del tabernero (escudero, monje, cazadora o aprendiz).' },
    ],
    combate: 'El [[n:Ogre]] aparece en las últimas oleadas: déjale a los centinelas y céntrate en él.',
    desbloquea: 'Armaduras del tabernero (híbridas con invocación) y el nivel 3 tras Gólem.',
    listoCuando: 'Lo has superado o lo aplazas (es opcional).',
    completadaCuando: B('downedDD2InvasionT2'),
    conserva: 'Las [[Defender Medal]].',
    avisos: [],
    fuentes: [W('Old One\'s Army'), W('Tavernkeep')],
  },
  {
    id: 'eclipse', capitulo: 'hardmode', titulo: 'Eclipse', tipo: 'evento', opcional: true,
    ubicaciones: [Z('superficie')],
    vida: { min: 460, max: 500, texto: '460–500' },
    donde: 'Superficie, de día.',
    invocacion: { objeto: 'Solar Tablet', donde: 'De día.', notas: 'Llega sola (1 de cada 20 días) tras vencer a un jefe mecánico. La [[Solar Tablet]] se fabrica con 8 [[Solar Tablet Fragment]] de los lagartos del Templo.' },
    preparate: 'Tu mejor equipo de modo difícil: los monstruos del Eclipse son de los más duros antes de Plantera.',
    porClase: {},
    tareas: [
      { condicion: M, texto: 'Sobrevive a un Eclipse.' },
      { condicion: PA('Death Sickle', 'Butcher\'s Chainsaw', 'Deadly Sphere Staff', 'Toxic Flask', 'Nail Gun', 'Psycho Knife', 'Eye Spring', 'Broken Hero Sword', 'Moon Stone', 'Brand of the Inferno', 'Neptune\'s Shell'), opcional: true, texto: 'Opcional: consigue alguno de sus objetos ([[Death Sickle]], [[Butcher\'s Chainsaw]], [[Moon Stone]]…).' },
      { condicion: P('Broken Hero Sword'), clases: ['cuerpo_a_cuerpo'], texto: 'Tras los tres mecánicos, [[Mothron]] suelta la [[Broken Hero Sword]], pieza de la [[Terra Blade]].' },
    ],
    combate: 'Muchos enemigos fuertes a la vez; el [[Mothron]] (tras los tres mecánicos) vuela y suelta crías. Lucha desde una posición con techo.',
    desbloquea: 'Componentes para la [[Terra Blade]] y armas únicas.',
    listoCuando: 'Lo has superado o lo aplazas (es opcional).',
    completadaCuando: null,
    conserva: 'La [[Broken Hero Sword]].',
    avisos: [],
    fuentes: [W('Solar Eclipse'), W('Mothron'), W('Broken Hero Sword')],
  },
  {
    id: 'plantera', capitulo: 'hardmode', titulo: '[[Plantera]]', tipo: 'jefe', jefes: ['Plantera'],
    ubicaciones: [Z('jungla_subterranea')],
    vida: { min: 500, max: 500, texto: '500' },
    donde: 'La jungla subterránea, donde rompas su bulbo.',
    invocacion: { objeto: null, donde: 'Rompe un bulbo de Plantera (flor rosa grande) en la jungla subterránea.', notas: 'Los bulbos solo aparecen tras vencer a los tres jefes mecánicos.' },
    preparate: 'Una arena excavada en la jungla subterránea (túneles cruzados o un recinto amplio), armadura de clorofita o sagrada, 500 de vida y pociones. No te alejes demasiado de la jungla: se enfurece.',
    porClase: {
      cuerpo_a_cuerpo: 'Armadura de clorofita (máscara) o sagrada y la [[True Excalibur]] o la [[Chlorophyte Partisan]].',
      distancia: 'La [[Megashark]] con [[Chlorophyte Bullet]] (que persiguen al blanco).',
      magia: 'El [[Rainbow Rod]], el [[Magical Harp]] o el [[Crystal Storm]].',
      invocacion: 'El [[Optic Staff]] y la armadura de araña o sagrada.',
    },
    tareas: [
      { condicion: B('downedMechBossAll'), texto: 'Vence a los tres jefes mecánicos para que aparezcan los bulbos.' },
      { condicion: M, texto: 'Prepara la arena alrededor del bulbo y retira la vegetación que estorbe.' },
      { condicion: B('downedPlantBoss'), texto: 'Derrota a Plantera.' },
      { condicion: P('Temple Key'), texto: 'Guarda la [[Temple Key]]: abre la puerta del Templo lihzahrd.' },
      { condicion: NPC('Cyborg'), texto: 'Recibe al [[Cyborg]] en tu pueblo: vende cohetes para los lanzacohetes.' },
    ],
    combate: 'En la primera fase dispara semillas y se mueve agarrada a las paredes; en la segunda suelta tentáculos y se vuelve más agresiva. Dibuja círculos alrededor de ella y no te quedes en un rincón.',
    desbloquea: 'El Templo, los cofres de bioma de la Mazmorra, las lunas de eventos y nuevos enemigos en la Mazmorra. Es el gran salto del modo difícil.',
    listoCuando: 'Plantera está vencida y tienes la llave del Templo.',
    completadaCuando: B('downedPlantBoss'),
    conserva: 'La [[Temple Key]] y la [[Seedler]] si cae (pieza de la [[Zenith]]).',
    avisos: [{ modos: ['experto', 'maestro'], texto: 'En Experto la [[Temple Key]] viene en la bolsa del tesoro, junto con el [[Spore Sac]].' }],
    fuentes: [W('Plantera'), W('Plantera\'s Bulb'), W('Temple Key')],
  },

  // =========================================================== Tras Plantera
  {
    id: 'mazmorra2', capitulo: 'postplantera', titulo: 'La Mazmorra tras Plantera', tipo: 'exploracion',
    ubicaciones: [PT('mazmorra'), Z('mazmorra')],
    vida: { min: 500, max: 500, texto: '500' },
    donde: 'La Mazmorra, ahora con enemigos nuevos.',
    preparate: 'Tu equipo tras Plantera y pociones: los nuevos esqueletos y lanzadores pegan muy fuerte.',
    porClase: {
      cuerpo_a_cuerpo: 'El [[Paladin\'s Shield]] (de los paladines) es uno de los mejores accesorios defensivos.',
      distancia: 'El [[Sniper Rifle]], la [[Tactical Shotgun]] y el [[Rocket Launcher]] salen de sus esqueletos.',
      magia: 'El [[Spectre Staff]], el [[Inferno Fork]] y el [[Shadowbeam Staff]] salen de sus lanzadores.',
      invocacion: 'La armadura espectral no es de invocación: céntrate en el [[Ectoplasm]] para la [[Pumpkin Moon Medallion]].',
    },
    tareas: [
      { condicion: P('Ectoplasm', 10), texto: 'Reúne [[Ectoplasm]] (lo sueltan los espíritus de la Mazmorra).' },
      { condicion: PA('Spectre Hood', 'Spectre Mask', 'Spectre Robe', 'Spectre Pants'), clases: ['magia'], texto: 'Fabrica la armadura espectral.' },
      { condicion: PA('Piranha Gun', 'Scourge of the Corruptor', 'Vampire Knives', 'Rainbow Gun', 'Staff of the Frost Hydra', 'Desert Tiger Staff'), texto: 'Abre un cofre de bioma de la Mazmorra con su llave (las llaves caen de enemigos de cada bioma y solo funcionan tras Plantera).' },
      { condicion: PA('Paladin\'s Shield', 'Sniper Rifle', 'Tactical Shotgun', 'Rocket Launcher', 'Spectre Staff', 'Inferno Fork', 'Shadowbeam Staff', 'Kraken'), opcional: true, texto: 'Opcional: consigue un arma o accesorio de los enemigos nuevos de la Mazmorra.' },
    ],
    combate: 'Los paladines resisten mucho y los lanzadores atraviesan paredes. Avanza poco a poco y elimina primero a los que disparan.',
    desbloquea: 'Ectoplasma para las lunas de eventos y la armadura espectral, y las mejores armas de cofre del modo difícil.',
    listoCuando: 'Tienes ectoplasma y, si quieres, un arma de cofre de bioma.',
    completadaCuando: P('Ectoplasm', 10),
    conserva: 'El [[Ectoplasm]] sobrante: la [[Pumpkin Moon Medallion]] y el [[Naughty Present]] lo piden.',
    avisos: [],
    fuentes: [W('The Dungeon'), W('Ectoplasm'), W('Biome Chest'), W('Spectre armor')],
  },
  {
    id: 'templo', capitulo: 'postplantera', titulo: 'El Templo lihzahrd', tipo: 'exploracion',
    ubicaciones: [Z('templo'), Z('jungla_subterranea')],
    vida: { min: 500, max: 500, texto: '500' },
    donde: 'El Templo, dentro de la jungla subterránea.',
    preparate: 'La [[Temple Key]], pociones y alas. El Templo está lleno de trampas: dardos, lanzas y bolas de pinchos.',
    porClase: {},
    tareas: [
      { condicion: M, texto: 'Abre la puerta del Templo con la [[Temple Key]] y avanza hasta la sala del altar.' },
      { condicion: P('Lihzahrd Power Cell'), texto: 'Consigue una [[Lihzahrd Power Cell]] (cofres del Templo y lagartos).' },
      { condicion: P('Solar Tablet Fragment'), opcional: true, texto: 'Opcional: guarda [[Solar Tablet Fragment]] para provocar Eclipses.' },
    ],
    combate: 'Los lagartos y las serpientes voladoras pegan fuerte; las trampas hacen más daño que los enemigos. Desactívalas o rómpelas con cuidado.',
    desbloquea: 'El altar de Gólem ({p:golem}).',
    listoCuando: 'Tienes una célula de energía y has llegado al altar.',
    completadaCuando: ALGUNA(P('Lihzahrd Power Cell'), B('downedGolemBoss')),
    conserva: 'Las células de energía de sobra (sirven para repetir a Gólem).',
    avisos: [],
    fuentes: [W('Jungle Temple'), W('Lihzahrd Power Cell'), W('Temple Key')],
  },
  {
    id: 'golem', capitulo: 'postplantera', titulo: '[[Golem]]', tipo: 'jefe', jefes: ['Golem'],
    ubicaciones: [Z('templo')],
    vida: { min: 500, max: 500, texto: '500' },
    donde: 'El altar del Templo lihzahrd.',
    invocacion: { objeto: 'Lihzahrd Power Cell', donde: 'Úsala en el [[Lihzahrd Altar]] del Templo.', notas: 'Las células salen de los cofres del Templo y de sus enemigos.' },
    preparate: 'Limpia la sala del altar de trampas y pon plataformas en varias alturas. Tu mejor equipo tras Plantera.',
    porClase: {
      cuerpo_a_cuerpo: 'Armadura de tortuga o de clorofita y la [[True Excalibur]] o un yoyó tras Plantera.',
      distancia: 'Armadura de piñonita o de clorofita y la [[Megashark]] o el [[Venus Magnum]].',
      magia: 'Armadura espectral y el [[Spectre Staff]] o el [[Leaf Blower]].',
      invocacion: 'Armadura tétrica si ya fuiste a la Luna calabaza, o la armadura de tiki, y el [[Pygmy Staff]] o el [[Raven Staff]].',
    },
    tareas: [
      { condicion: ALGUNA(P('Lihzahrd Power Cell'), B('downedGolemBoss')), texto: 'Lleva una [[Lihzahrd Power Cell]] al altar.' },
      { condicion: B('downedGolemBoss'), texto: 'Derrota a Gólem.' },
      { condicion: P('Picksaw'), texto: 'Consigue la [[Picksaw]] (puede tardar varias peleas): pica los ladrillos del Templo.' },
      { condicion: P('Beetle Husk'), clases: ['cuerpo_a_cuerpo'], texto: 'Recoge [[Beetle Husk]] para la armadura de escarabajo.' },
    ],
    combate: 'Primero destruye sus puños y luego la cabeza; en la segunda fase la cabeza se separa y dispara láseres. Mantente en plataformas sobre él.',
    desbloquea: 'El Sectario lunático en la entrada de la Mazmorra, la Locura marciana y el nivel 3 del Ejército del Antiguo.',
    listoCuando: 'Gólem está vencido.',
    completadaCuando: B('downedGolemBoss'),
    conserva: 'Las [[Beetle Husk]] y la [[Picksaw]].',
    avisos: [{ modos: ['experto', 'maestro'], texto: 'En Experto, su bolsa da el [[Shiny Stone]] (regeneración rápida estando quieto).' }],
    fuentes: [W('Golem'), W('Lihzahrd Altar'), W('Picksaw')],
  },
  {
    id: 'fishron', capitulo: 'postplantera', titulo: '[[Duke Fishron]]', tipo: 'jefe', opcional: true, jefes: ['Duke Fishron'],
    ubicaciones: [Z('oceano'), Z('setas')],
    vida: { min: 500, max: 500, texto: '500' },
    donde: 'El Océano.',
    invocacion: { objeto: 'Truffle Worm', donde: 'Pescando en el Océano con el gusano como cebo.', notas: 'El [[o:Truffle Worm]] es un bicho que vive en los champiñones brillantes subterráneos en modo difícil; se coge con una red.' },
    preparate: 'Una plataforma larga sobre el Océano, alas rápidas y tu mejor arma: es de los jefes más duros antes del final.',
    porClase: {},
    tareas: [
      { condicion: ALGUNA(P('Truffle Worm'), B('downedFishron')), texto: 'Captura un [[o:Truffle Worm]] con una red en el bioma de champiñones.' },
      { condicion: B('downedFishron'), texto: 'Pesca con él en el Océano y derrota al Duque Fishron.' },
      { condicion: PA('Flairon', 'Tsunami', 'Razorblade Typhoon', 'Bubble Gun', 'Tempest Staff', 'Fishron Wings'), opcional: true, texto: 'Opcional: consigue una de sus armas o las [[Fishron Wings]].' },
    ],
    combate: 'Embiste tres veces seguidas y suelta tornados; si sales del Océano se enfurece. Esquiva en vertical con alas.',
    desbloquea: 'Armas de alto nivel para cada clase.',
    listoCuando: 'Lo has vencido o lo aplazas (es opcional).',
    completadaCuando: B('downedFishron'),
    conserva: 'Las [[Fishron Wings]] si caen.',
    avisos: [],
    fuentes: [W('Duke Fishron'), W('Truffle Worm')],
  },
  {
    id: 'empress', capitulo: 'postplantera', titulo: '[[Empress of Light]]', tipo: 'jefe', opcional: true, jefes: ['Empress of Light'],
    ubicaciones: [Z('sagrado')],
    vida: { min: 500, max: 500, texto: '500' },
    donde: 'Lo Sagrado de la superficie, de noche.',
    invocacion: { objeto: null, donde: 'En Lo Sagrado de la superficie, de noche.', notas: 'Mata una [[n:Prismatic Lacewing]]: aparecen tras vencer a Plantera, en la primera mitad de la noche.' },
    preparate: 'Alas rápidas, una arena muy abierta y tu mejor equipo. De día se enfurece y mata de un golpe.',
    porClase: {},
    tareas: [
      { condicion: B('downedPlantBoss'), texto: 'Vence a Plantera para que aparezcan las crisopas prismáticas.' },
      { condicion: B('downedEmpressOfLight'), texto: 'Derrota a la Emperatriz de la luz de noche.' },
      { condicion: PA('Nightglow', 'Starlight', 'Eventide', 'Kaleidoscope', 'Empress Wings', 'Terraprisma'), opcional: true, texto: 'Opcional: consigue alguna de sus armas. La [[Terraprisma]] solo cae si la vences de día.' },
    ],
    combate: 'Ataques de luz en patrones de abanico, espadas y rayos. Muévete en círculos amplios y memoriza cada patrón.',
    desbloquea: 'Armas de las cuatro clases y, como gran desafío, la [[Terraprisma]].',
    listoCuando: 'La has vencido o la aplazas (es opcional).',
    completadaCuando: B('downedEmpressOfLight'),
    conserva: 'Nada imprescindible.',
    avisos: [],
    fuentes: [W('Empress of Light'), W('Prismatic Lacewing'), W('Terraprisma')],
  },
  {
    id: 'pumpkin', capitulo: 'postplantera', titulo: 'Luna calabaza', tipo: 'evento', opcional: true,
    ubicaciones: [PT('spawn'), Z('superficie')],
    vida: { min: 500, max: 500, texto: '500' },
    donde: 'Superficie, de noche.',
    invocacion: { objeto: 'Pumpkin Moon Medallion', donde: 'De noche.', notas: 'Se fabrica en el yunque de modo difícil con 30 [[Pumpkin]], 5 [[Ectoplasm]] y 10 [[Hallowed Bar]].' },
    preparate: 'Una arena con plataformas, hogueras y estaciones de buff, tu mejor equipo y pociones. Cuanto más avances en las oleadas, mejores premios.',
    porClase: {},
    tareas: [
      { condicion: ALGUNA(P('Pumpkin Moon Medallion'), B('downedHalloweenTree'), B('downedHalloweenKing')), texto: 'Fabrica la [[Pumpkin Moon Medallion]].' },
      { condicion: B('downedHalloweenTree'), texto: 'Derrota al [[Mourning Wood]].' },
      { condicion: B('downedHalloweenKing'), texto: 'Derrota al [[Pumpking]].' },
      { condicion: PA('The Horseman\'s Blade', 'Raven Staff', 'Bat Scepter', 'Candy Corn Rifle', 'Jack \'O Lantern Launcher', 'Black Fairy Dust', 'Spooky Wood'), opcional: true, texto: 'Opcional: consigue sus premios; la [[The Horseman\'s Blade]] es pieza de la [[Zenith]].' },
    ],
    combate: 'Las oleadas mezclan enemigos y minijefes. Mata rápido a los minijefes para sumar puntos y mantente en el centro de la arena.',
    desbloquea: 'La armadura tétrica (invocación) con [[Spooky Wood]], y armas de alto nivel.',
    listoCuando: 'Has vencido a sus dos jefes o la aplazas (es opcional).',
    completadaCuando: B('downedHalloweenKing'),
    conserva: 'La [[The Horseman\'s Blade]] (pieza de la [[Zenith]]).',
    avisos: [],
    fuentes: [W('Pumpkin Moon'), W('Pumpkin Moon Medallion'), W('Spooky armor')],
  },
  {
    id: 'frostmoon', capitulo: 'postplantera', titulo: 'Luna Gélida', tipo: 'evento', opcional: true,
    ubicaciones: [PT('spawn'), Z('superficie')],
    vida: { min: 500, max: 500, texto: '500' },
    donde: 'Superficie, de noche.',
    invocacion: { objeto: 'Naughty Present', donde: 'De noche.', notas: 'Se fabrica en el yunque de modo difícil con 20 [[Silk]], 5 [[Ectoplasm]] y 5 [[Soul of Fright]].' },
    preparate: 'La misma arena que para la Luna calabaza y tu mejor equipo: sus jefes son más duros.',
    porClase: {},
    tareas: [
      { condicion: ALGUNA(P('Naughty Present'), B('downedChristmasTree'), B('downedChristmasSantank'), B('downedChristmasIceQueen')), texto: 'Fabrica el [[Naughty Present]].' },
      { condicion: B('downedChristmasTree'), texto: 'Derrota al [[Everscream]].' },
      { condicion: B('downedChristmasSantank'), texto: 'Derrota a [[Santa-NK1]].' },
      { condicion: B('downedChristmasIceQueen'), texto: 'Derrota a la [[Ice Queen]].' },
      { condicion: PA('North Pole', 'Snowman Cannon', 'Blizzard Staff', 'Razorpine', 'Elf Melter', 'Chain Gun', 'Christmas Tree Sword', 'Festive Wings', 'Staff of the Frost Hydra'), opcional: true, texto: 'Opcional: consigue alguno de sus premios.' },
    ],
    combate: 'Igual que la Luna calabaza, pero los jefes aguantan más. La [[Ice Queen]] vuela y dispara hielo: es la más peligrosa.',
    desbloquea: 'Armas de alto nivel y las [[Festive Wings]].',
    listoCuando: 'Has vencido a sus tres jefes o la aplazas (es opcional).',
    completadaCuando: B('downedChristmasIceQueen'),
    conserva: 'Nada imprescindible.',
    avisos: [],
    fuentes: [W('Frost Moon'), W('Naughty Present')],
  },
  {
    id: 'dd2t3', capitulo: 'postplantera', titulo: 'Ejército del Antiguo (nivel 3)', tipo: 'evento', opcional: true,
    ubicaciones: [PT('spawn')],
    vida: { min: 500, max: 500, texto: '500' },
    donde: 'Donde tengas el [[Eternia Crystal Stand]].',
    invocacion: { objeto: 'Eternia Crystal', donde: 'Sobre el soporte.', notas: 'El nivel 3 se activa tras vencer a Gólem.' },
    preparate: 'Centinelas de nivel 3, armadura de nivel Gólem y alas: al final llega [[Betsy]], un dragón.',
    porClase: {},
    tareas: [
      { condicion: B('downedGolemBoss'), texto: 'Vence a Gólem para desbloquear el nivel 3.' },
      { condicion: B('downedDD2InvasionT3'), texto: 'Supera el nivel 3 y derrota a [[Betsy]].' },
      { condicion: PA('Flying Dragon', 'Sky Dragon\'s Fury', 'Aerial Bane', 'Betsy\'s Wrath', 'Betsy\'s Wings'), opcional: true, texto: 'Opcional: consigue una de sus armas o sus alas.' },
    ],
    combate: 'Betsy embiste y escupe fuego; los centinelas no la alcanzan bien: combátela tú directamente.',
    desbloquea: 'Las armas de Betsy y las mejores armaduras del tabernero.',
    listoCuando: 'Lo has superado o lo aplazas (es opcional).',
    completadaCuando: B('downedDD2InvasionT3'),
    conserva: 'Las [[Defender Medal]].',
    avisos: [],
    fuentes: [W('Old One\'s Army'), W('Betsy')],
  },
  {
    id: 'martians', capitulo: 'postplantera', titulo: 'Locura marciana', tipo: 'evento', opcional: true,
    ubicaciones: [Z('superficie'), Z('cielo')],
    vida: { min: 500, max: 500, texto: '500' },
    donde: 'Las zonas exteriores del mundo, en la Superficie o en el espacio, donde vuela la sonda marciana.',
    invocacion: { objeto: null, donde: 'Deja que una sonda marciana te vea y escape.', notas: 'La sonda solo aparece tras vencer a Gólem.' },
    preparate: 'Alas, tu mejor equipo y una arena abierta: el [[Martian Saucer]] es el jefe final del evento.',
    porClase: {},
    tareas: [
      { condicion: B('downedGolemBoss'), texto: 'Vence a Gólem para que aparezcan las sondas.' },
      { condicion: B('downedMartians'), texto: 'Derrota la Locura marciana (incluido el platillo).' },
      { condicion: PA('Influx Waver', 'Xenopopper', 'Laser Machinegun', 'Charged Blaster Cannon', 'Electrosphere Launcher', 'Cosmic Car Key'), opcional: true, texto: 'Opcional: consigue una de sus armas; la [[Influx Waver]] es pieza de la [[Zenith]].' },
    ],
    combate: 'Muchos enemigos con escudos y rayos; el platillo dispara láseres en barrido. Destruye sus torretas primero.',
    desbloquea: 'Armas marcianas y el [[Cosmic Car Key]] (montura).',
    listoCuando: 'Lo has superado o lo aplazas (es opcional).',
    completadaCuando: B('downedMartians'),
    conserva: 'La [[Influx Waver]] (pieza de la [[Zenith]]).',
    avisos: [],
    fuentes: [W('Martian Madness'), W('Martian Probe'), W('Martian Saucer')],
  },

  // =========================================================== El Señor de la Luna y despues
  {
    id: 'cultist', capitulo: 'finjuego', titulo: '[[Lunatic Cultist]]', tipo: 'jefe', jefes: ['Lunatic Cultist'],
    ubicaciones: [PT('mazmorra'), Z('mazmorra')],
    vida: { min: 500, max: 500, texto: '500' },
    donde: 'La entrada de la Mazmorra.',
    invocacion: { objeto: null, donde: 'Frente a la Mazmorra, donde rezan los devotos.', notas: 'Tras vencer a Gólem aparecen sectarios rezando ante la Mazmorra: atácalos para que salga el jefe.' },
    preparate: 'Una plataforma frente a la Mazmorra, alas y tu mejor equipo tras Gólem.',
    porClase: {
      cuerpo_a_cuerpo: 'Armadura de escarabajo y un arma rápida como la [[Influx Waver]] o la [[The Horseman\'s Blade]].',
      distancia: 'Armadura de piñonita y la [[Chain Gun]] o el [[Tsunami]].',
      magia: 'Armadura espectral y la [[Razorblade Typhoon]] o el [[Nebula Blaze]] tras las torres.',
      invocacion: 'Armadura tétrica y el [[Raven Staff]] o la [[Tempest Staff]].',
    },
    tareas: [
      { condicion: B('downedGolemBoss'), texto: 'Vence a Gólem para que aparezcan los sectarios.' },
      { condicion: B('downedAncientCultist'), texto: 'Derrota al Sectario lunático.' },
      { condicion: P('Ancient Manipulator'), texto: 'Recoge el [[Ancient Manipulator]]: es la estación de fabricación del final del juego.' },
    ],
    combate: 'Lanza bolas de fuego, rayos y hielo, y crea copias de sí mismo: el original es el que lanza el ataque. Mátalas rápido o te superan.',
    desbloquea: 'Las cuatro torres celestiales aparecen en el mundo ({p:pillars}).',
    listoCuando: 'El Sectario está vencido.',
    completadaCuando: B('downedAncientCultist'),
    conserva: 'El [[Ancient Manipulator]].',
    avisos: [],
    fuentes: [W('Lunatic Cultist'), W('Ancient Manipulator')],
  },
  {
    id: 'pillars', capitulo: 'finjuego', titulo: 'Torres celestiales', tipo: 'evento',
    ubicaciones: [Z('superficie')],
    vida: { min: 500, max: 500, texto: '500' },
    donde: 'Repartidas por la Superficie del mundo.',
    preparate: 'Alas, tu mejor equipo y pociones. Cada torre tiene un escudo que cae tras matar 100 enemigos a su alrededor (50 si ya venciste al Señor de la Luna).',
    porClase: {
      cuerpo_a_cuerpo: 'Empieza por la Columna solar: sus fragmentos dan las armas y la armadura cuerpo a cuerpo.',
      distancia: 'La Columna de vórtice: sus enemigos se teletransportan, ojo a la gravedad.',
      magia: 'La Columna de nebulosa: sus enemigos te debilitan, mátalos rápido.',
      invocacion: 'La Columna de polvo estelar: los esbirros limpian bien sus enemigos.',
    },
    tareas: [
      { condicion: P('Solar Fragment'), texto: 'Destruye la Columna solar y recoge sus fragmentos.' },
      { condicion: P('Vortex Fragment'), texto: 'Destruye la Columna de vórtice.' },
      { condicion: P('Nebula Fragment'), texto: 'Destruye la Columna de nebulosa.' },
      { condicion: P('Stardust Fragment'), texto: 'Destruye la Columna de polvo estelar.' },
      { condicion: B('downedTowers'), texto: 'Con las cuatro torres caídas, prepárate: el Señor de la Luna llega en un minuto.' },
    ],
    combate: 'Mata enemigos cerca de la torre hasta romper su escudo y luego ataca a la torre. Cada columna tiene su propio peligro: no te quedes quieto.',
    desbloquea: 'Fragmentos para las armas y armaduras lunares, y la llegada del Señor de la Luna.',
    listoCuando: 'Las cuatro torres están destruidas.',
    completadaCuando: B('downedTowers'),
    conserva: 'Los fragmentos de las cuatro torres: la [[Celestial Sigil]] y las armaduras lunares los piden.',
    avisos: [],
    fuentes: [W('Celestial Pillars'), W('Lunar Events')],
  },
  {
    id: 'moonlord', capitulo: 'finjuego', titulo: '[[Moon Lord]]', tipo: 'jefe', jefes: ['Moon Lord'],
    ubicaciones: [PT('spawn'), Z('superficie')],
    vida: { min: 500, max: 500, texto: '500' },
    donde: 'Aparece sobre ti, estés donde estés.',
    invocacion: { objeto: 'Celestial Sigil', donde: 'En cualquier sitio.', notas: 'Llega solo un minuto después de caer la última torre. Para repetirlo, la [[Celestial Sigil]] se fabrica con 12 fragmentos de cada torre en el [[Ancient Manipulator]].' },
    preparate: 'Una arena enorme con plataformas, hogueras, [[Heart Lantern]], estaciones de buff y tus mejores pociones. Las mejores armas de torre o de evento.',
    porClase: {
      cuerpo_a_cuerpo: 'Armadura de escarabajo o solar y la [[Solar Eruption]] o la [[Daybreak]].',
      distancia: 'Armadura de piñonita o de vórtice y el [[Phantasm]] o el [[Vortex Beater]].',
      magia: 'Armadura espectral o de nebulosa y el [[Nebula Blaze]] o el [[Nebula Arcanum]].',
      invocacion: 'Armadura tétrica o de polvo estelar y el [[Stardust Dragon Staff]] o el [[Stardust Cell Staff]].',
    },
    tareas: [
      { condicion: M, texto: 'Construye una arena muy ancha con plataformas en varias alturas.' },
      { condicion: B('downedMoonlord'), texto: 'Derrota al Señor de la Luna.' },
      { condicion: P('Luminite Bar'), texto: 'Funde [[Luminite]] en el [[Ancient Manipulator]].' },
      { condicion: PA('Meowmere', 'Terrarian', 'Star Wrath', 'S.D.M.G.', 'Last Prism', 'Lunar Flare', 'Rainbow Crystal Staff', 'Lunar Portal Staff', 'Celebration Mk2', 'Portal Gun'), texto: 'Recoge sus armas y el [[Portal Gun]].' },
    ],
    combate: 'Primero rompe los ojos de las manos y luego el de la cabeza; al final, el corazón. Su rayo mortal sigue tu posición: no te quedes quieto delante de él. Los ojos fantasma persiguen: mantente en movimiento.',
    desbloquea: 'La [[Luminite]], las armaduras lunares y las mejores armas del juego.',
    listoCuando: 'El Señor de la Luna está vencido.',
    completadaCuando: B('downedMoonlord'),
    conserva: 'El [[Meowmere]] y el [[Star Wrath]] si caen (piezas de la [[Zenith]]).',
    avisos: [{ modos: ['experto', 'maestro'], texto: 'En Experto, su bolsa da el [[Gravity Globe]] (invierte la gravedad a voluntad) y el [[Suspicious Looking Tentacle]].' }],
    fuentes: [W('Moon Lord'), W('Celestial Sigil'), W('Luminite')],
  },
  {
    id: 'postmoon', capitulo: 'finjuego', titulo: 'Después del Señor de la Luna', tipo: 'preparacion',
    ubicaciones: [PT('spawn')],
    vida: { min: 500, max: 500, texto: '500' },
    donde: 'Tu base y el [[Ancient Manipulator]].',
    preparate: 'Fragmentos de las cuatro torres y [[Luminite Bar]].',
    porClase: {
      cuerpo_a_cuerpo: 'Armadura solar: [[Solar Flare Helmet]], [[Solar Flare Breastplate]] y [[Solar Flare Leggings]].',
      distancia: 'Armadura de vórtice: [[Vortex Helmet]], [[Vortex Breastplate]] y [[Vortex Leggings]].',
      magia: 'Armadura de nebulosa: [[Nebula Helmet]], [[Nebula Breastplate]] y [[Nebula Leggings]].',
      invocacion: 'Armadura de polvo estelar: [[Stardust Helmet]], [[Stardust Plate]] y [[Stardust Leggings]].',
    },
    tareas: [
      { condicion: PA('Solar Flare Breastplate', 'Vortex Breastplate', 'Nebula Breastplate', 'Stardust Plate'), texto: 'Fabrica la armadura lunar de tu clase.' },
      { condicion: PA('Solar Wings', 'Vortex Booster', 'Nebula Mantle', 'Stardust Wings', 'Celestial Starboard'), texto: 'Fabrica unas alas lunares o la [[Celestial Starboard]].' },
      { condicion: P('Drill Containment Unit'), opcional: true, texto: 'Opcional: la [[Drill Containment Unit]], una montura que excava muy rápido.' },
      { condicion: DEF(80), texto: 'Llega a 80 de defensa con la armadura y los accesorios del final.' },
    ],
    combate: 'Ya no hay jefes nuevos: repite el Señor de la Luna y los eventos para completar tu equipo.',
    desbloquea: 'El final del juego: completa colecciones, construye y prueba los desafíos ({p:zenith}).',
    listoCuando: 'Llevas la armadura lunar de tu clase.',
    completadaCuando: PA('Solar Flare Breastplate', 'Vortex Breastplate', 'Nebula Breastplate', 'Stardust Plate'),
    conserva: 'Nada especial: ya tienes acceso a todo.',
    avisos: [],
    fuentes: [W('Luminite'), W('Solar Flare armor'), W('Vortex armor'), W('Nebula armor'), W('Stardust armor')],
  },
  {
    id: 'mejoras', capitulo: 'finjuego', titulo: 'Mejoras permanentes que te falten', tipo: 'desafio', opcional: true,
    ubicaciones: [Z('eter')],
    vida: { min: 500, max: 500, texto: '500' },
    donde: 'El Éter (fulgor), la tienda del [[Skeleton Merchant]] en el subsuelo y la pesca en Luna de Sangre.',
    preparate: 'Repasa {a:vida}: cada mejora tiene su origen.',
    porClase: {},
    tareas: [
      { condicion: MEJ('aegisCrystal'), texto: 'Usa el [[Vital Crystal]] (un [[Life Crystal]] en el fulgor).' },
      { condicion: MEJ('aegisFruit'), texto: 'Usa la [[Aegis Fruit]] (una [[Life Fruit]] en el fulgor).' },
      { condicion: MEJ('arcaneCrystal'), texto: 'Usa el [[Arcane Crystal]] (un [[Mana Crystal]] en el fulgor).' },
      { condicion: MEJ('galaxyPearl'), texto: 'Usa la [[Galaxy Pearl]] (una [[Pink Pearl]] en el fulgor).' },
      { condicion: MEJ('gummyWorm'), texto: 'Usa el [[Gummy Worm]] (un [[o:Gold Worm]] en el fulgor).' },
      { condicion: MEJ('ambrosia'), texto: 'Usa la [[Ambrosia]] (cualquier fruta en el fulgor).' },
      { condicion: MEJ('artisanBread'), texto: 'Cómete el [[Artisan Loaf]]: lo vende el [[Skeleton Merchant]] en las fases cercanas a la luna nueva.' },
      { condicion: B('combatBookWasUsed'), texto: 'Usa el [[Advanced Combat Techniques]] (se pesca en Luna de Sangre): tus vecinos se defienden mejor.' },
      { condicion: B('combatBookVolumeTwoWasUsed'), texto: 'Usa el [[Advanced Combat Techniques: Volume Two]] (un [[Spell Tome]] en el fulgor).' },
      { condicion: B('peddlersSatchelWasUsed'), texto: 'Usa el [[Peddler\'s Satchel]] (un [[Peddler\'s Hat]] en el fulgor): el [[Traveling Merchant]] vende más.' },
    ],
    combate: 'Sin combate.',
    desbloquea: 'Pequeñas mejoras permanentes de vida, defensa, maná, suerte, velocidad de cavado y de uso. Ver {a:vida}.',
    listoCuando: 'Has usado las que te interesan.',
    completadaCuando: TODAS(MEJ('aegisCrystal'), MEJ('aegisFruit'), MEJ('arcaneCrystal'), MEJ('galaxyPearl'), MEJ('gummyWorm'), MEJ('ambrosia'), MEJ('artisanBread')),
    conserva: 'Nada: todas se consumen.',
    avisos: [{ modos: ['clasico', 'viaje'], texto: 'El [[Demon Heart]] sigue siendo exclusivo de Experto y Maestro: en Clásico no aparece en esta lista.' }],
    fuentes: [W('Permanent boosters'), W('Shimmer'), W('Artisan Loaf'), W('Advanced Combat Techniques')],
  },
  {
    id: 'zenith', capitulo: 'finjuego', titulo: 'La [[Zenith]]', tipo: 'desafio', opcional: true,
    ubicaciones: [PT('spawn')],
    vida: { min: 500, max: 500, texto: '500' },
    donde: 'Tu base: la Zenit se fabrica en el yunque de modo difícil.',
    preparate: 'Las diez espadas de la receta, que vienen de casi toda la partida.',
    porClase: {
      cuerpo_a_cuerpo: 'Es el arma cuerpo a cuerpo definitiva del juego.',
      distancia: 'No es de tu clase, pero sirve como reto de colección.',
      magia: 'No es de tu clase, pero sirve como reto de colección.',
      invocacion: 'No es de tu clase, pero sirve como reto de colección.',
    },
    tareas: [
      { condicion: P('Terra Blade'), texto: 'Fabrica la [[Terra Blade]] ([[True Night\'s Edge]] + [[True Excalibur]] + [[Broken Hero Sword]]).' },
      { condicion: TODAS(P('Meowmere'), P('Star Wrath')), texto: 'Consigue el [[Meowmere]] y el [[Star Wrath]] del Señor de la Luna.' },
      { condicion: TODAS(P('Influx Waver'), P('The Horseman\'s Blade'), P('Seedler')), texto: 'Consigue la [[Influx Waver]] (marcianos), la [[The Horseman\'s Blade]] (Pumpking) y la [[Seedler]] (Plantera).' },
      { condicion: TODAS(P('Starfury'), P('Bee Keeper'), P('o:Enchanted Sword'), P('Copper Shortsword')), texto: 'Recupera las del principio: [[Starfury]], [[Bee Keeper]], [[o:Enchanted Sword]] y [[Copper Shortsword]].' },
      { condicion: P('Zenith'), texto: 'Fabrica la [[Zenith]].' },
    ],
    combate: 'Sin combate: es un reto de colección.',
    desbloquea: 'El arma más poderosa del juego.',
    listoCuando: 'Tienes la Zenit.',
    completadaCuando: P('Zenith'),
    conserva: 'Todo hasta fabricarla: cada una de las diez espadas es imprescindible.',
    avisos: [],
    fuentes: [W('Zenith'), W('Terra Blade')],
  },
];

module.exports = { paradas };
